/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:3.1-60.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.82-88.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.13-4.14" *)
  wire _126_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.13-4.14" *)
  wire _127_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.13-4.14" *)
  wire _128_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.13-4.14" *)
  wire _129_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.15-4.16" *)
  wire _130_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.15-4.16" *)
  wire _131_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.15-4.16" *)
  wire _132_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.15-4.16" *)
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:32.12-32.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:86.13-86.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:86.15-86.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:143.8-143.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.7-142.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.17-142.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:143.13-143.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.12-142.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.22-142.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:143.8-143.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.7-142.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.17-142.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:143.13-143.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.12-142.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:142.22-142.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.46-88.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.144-88.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.54-88.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.162-88.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.126-88.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.90-88.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.123-88.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.49-88.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.67-88.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.77-88.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:107.8-107.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.62-88.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.16-88.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.11-88.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.36-88.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:109.8-109.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.72-88.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.93-88.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.118-88.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.21-88.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:111.8-111.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.147-88.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:137.8-137.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.7-136.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.17-136.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:136.12-136.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.82-88.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.26-88.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.41-88.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.98-88.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.103-88.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.31-88.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.6-88.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:88.108-88.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:87.14-87.15" *)
  wire [7:0] \add.s ;
  wire [4:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa4.z ;
  (* hdlname = "fa5 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.7-69.8" *)
  wire \fa5.a ;
  (* hdlname = "fa5 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.9-69.10" *)
  wire \fa5.b ;
  (* hdlname = "fa5 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:69.11-69.12" *)
  wire \fa5.c ;
  (* hdlname = "fa5 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.8-70.10" *)
  wire \fa5.cy ;
  (* hdlname = "fa5 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa5.h1.a ;
  (* hdlname = "fa5 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa5.h1.b ;
  (* hdlname = "fa5 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa5.h1.c ;
  (* hdlname = "fa5 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa5.h1.s ;
  (* hdlname = "fa5 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \fa5.h2.a ;
  (* hdlname = "fa5 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \fa5.h2.b ;
  (* hdlname = "fa5 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \fa5.h2.c ;
  (* hdlname = "fa5 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \fa5.h2.s ;
  (* hdlname = "fa5 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:70.11-70.13" *)
  wire \fa5.sm ;
  (* hdlname = "fa5 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.6-71.7" *)
  wire \fa5.x ;
  (* hdlname = "fa5 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.8-71.9" *)
  wire \fa5.y ;
  (* hdlname = "fa5 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:71.10-71.11" *)
  wire \fa5.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.7-63.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:63.9-63.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.8-64.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:64.10-64.11" *)
  wire \ha1.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:33.12-33.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_31b41f3fa0f24aba275cc1f2e49c83b7.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  BUF_X4 _136_ (
    .A(_126_),
    .Z(_048_)
  );
  AND2_X1 _137_ (
    .A1(_130_),
    .A2(_048_),
    .ZN(_007_)
  );
  BUF_X4 _138_ (
    .A(_127_),
    .Z(_049_)
  );
  NAND2_X1 _139_ (
    .A1(_130_),
    .A2(_049_),
    .ZN(_050_)
  );
  NAND2_X1 _140_ (
    .A1(_048_),
    .A2(_131_),
    .ZN(_051_)
  );
  XOR2_X1 _141_ (
    .A(_050_),
    .B(_051_),
    .Z(_000_)
  );
  NAND2_X1 _142_ (
    .A1(_131_),
    .A2(_049_),
    .ZN(_052_)
  );
  BUF_X8 _143_ (
    .A(_132_),
    .Z(_053_)
  );
  NAND3_X1 _144_ (
    .A1(_052_),
    .A2(_048_),
    .A3(_053_),
    .ZN(_054_)
  );
  NAND2_X2 _145_ (
    .A1(_048_),
    .A2(_053_),
    .ZN(_055_)
  );
  NAND3_X1 _146_ (
    .A1(_055_),
    .A2(_131_),
    .A3(_049_),
    .ZN(_056_)
  );
  NAND2_X2 _147_ (
    .A1(_054_),
    .A2(_056_),
    .ZN(_057_)
  );
  BUF_X4 _148_ (
    .A(_128_),
    .Z(_058_)
  );
  NAND2_X1 _149_ (
    .A1(_130_),
    .A2(_058_),
    .ZN(_059_)
  );
  INV_X1 _150_ (
    .A(_059_),
    .ZN(_060_)
  );
  XNOR2_X2 _151_ (
    .A(_057_),
    .B(_060_),
    .ZN(_061_)
  );
  NOR2_X1 _152_ (
    .A1(_050_),
    .A2(_051_),
    .ZN(_062_)
  );
  XNOR2_X1 _153_ (
    .A(_061_),
    .B(_062_),
    .ZN(_001_)
  );
  NOR2_X2 _154_ (
    .A1(_052_),
    .A2(_055_),
    .ZN(_063_)
  );
  AOI21_X4 _155_ (
    .A(_063_),
    .B1(_057_),
    .B2(_060_),
    .ZN(_064_)
  );
  NAND2_X4 _156_ (
    .A1(_053_),
    .A2(_049_),
    .ZN(_065_)
  );
  BUF_X8 _157_ (
    .A(_133_),
    .Z(_066_)
  );
  NAND3_X4 _158_ (
    .A1(_065_),
    .A2(_048_),
    .A3(_066_),
    .ZN(_067_)
  );
  NAND2_X4 _159_ (
    .A1(_048_),
    .A2(_066_),
    .ZN(_068_)
  );
  NAND3_X4 _160_ (
    .A1(_068_),
    .A2(_053_),
    .A3(_049_),
    .ZN(_069_)
  );
  NAND2_X4 _161_ (
    .A1(_131_),
    .A2(_058_),
    .ZN(_070_)
  );
  INV_X4 _162_ (
    .A(_070_),
    .ZN(_071_)
  );
  AND3_X4 _163_ (
    .A1(_067_),
    .A2(_069_),
    .A3(_071_),
    .ZN(_072_)
  );
  AOI21_X4 _164_ (
    .A(_071_),
    .B1(_067_),
    .B2(_069_),
    .ZN(_073_)
  );
  BUF_X2 _165_ (
    .A(_129_),
    .Z(_074_)
  );
  NAND2_X1 _166_ (
    .A1(_130_),
    .A2(_074_),
    .ZN(_075_)
  );
  NOR3_X4 _167_ (
    .A1(_072_),
    .A2(_073_),
    .A3(_075_),
    .ZN(_076_)
  );
  INV_X1 _168_ (
    .A(_075_),
    .ZN(_077_)
  );
  NAND2_X4 _169_ (
    .A1(_067_),
    .A2(_069_),
    .ZN(_078_)
  );
  NAND2_X4 _170_ (
    .A1(_078_),
    .A2(_070_),
    .ZN(_079_)
  );
  NAND3_X4 _171_ (
    .A1(_067_),
    .A2(_069_),
    .A3(_071_),
    .ZN(_080_)
  );
  AOI21_X2 _172_ (
    .A(_077_),
    .B1(_079_),
    .B2(_080_),
    .ZN(_081_)
  );
  OAI21_X2 _173_ (
    .A(_064_),
    .B1(_076_),
    .B2(_081_),
    .ZN(_082_)
  );
  NAND3_X4 _174_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_077_),
    .ZN(_083_)
  );
  OAI21_X4 _175_ (
    .A(_075_),
    .B1(_072_),
    .B2(_073_),
    .ZN(_084_)
  );
  INV_X1 _176_ (
    .A(_064_),
    .ZN(_085_)
  );
  NAND3_X2 _177_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_085_),
    .ZN(_086_)
  );
  NAND2_X1 _178_ (
    .A1(_082_),
    .A2(_086_),
    .ZN(_087_)
  );
  INV_X1 _179_ (
    .A(_062_),
    .ZN(_088_)
  );
  NOR2_X1 _180_ (
    .A1(_061_),
    .A2(_088_),
    .ZN(_089_)
  );
  XOR2_X1 _181_ (
    .A(_087_),
    .B(_089_),
    .Z(_002_)
  );
  NAND2_X4 _182_ (
    .A1(_078_),
    .A2(_071_),
    .ZN(_090_)
  );
  NOR2_X2 _183_ (
    .A1(_065_),
    .A2(_068_),
    .ZN(_091_)
  );
  INV_X1 _184_ (
    .A(_091_),
    .ZN(_092_)
  );
  NAND2_X4 _185_ (
    .A1(_053_),
    .A2(_058_),
    .ZN(_093_)
  );
  NAND3_X4 _186_ (
    .A1(_093_),
    .A2(_066_),
    .A3(_049_),
    .ZN(_094_)
  );
  NAND2_X4 _187_ (
    .A1(_066_),
    .A2(_049_),
    .ZN(_095_)
  );
  NAND3_X4 _188_ (
    .A1(_095_),
    .A2(_053_),
    .A3(_058_),
    .ZN(_096_)
  );
  NAND2_X2 _189_ (
    .A1(_131_),
    .A2(_074_),
    .ZN(_097_)
  );
  INV_X1 _190_ (
    .A(_097_),
    .ZN(_098_)
  );
  AND3_X1 _191_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_098_),
    .ZN(_099_)
  );
  AOI21_X1 _192_ (
    .A(_098_),
    .B1(_094_),
    .B2(_096_),
    .ZN(_100_)
  );
  OAI211_X2 _193_ (
    .A(_090_),
    .B(_092_),
    .C1(_099_),
    .C2(_100_),
    .ZN(_101_)
  );
  NAND2_X2 _194_ (
    .A1(_094_),
    .A2(_096_),
    .ZN(_102_)
  );
  NAND2_X1 _195_ (
    .A1(_102_),
    .A2(_097_),
    .ZN(_103_)
  );
  NAND3_X1 _196_ (
    .A1(_094_),
    .A2(_096_),
    .A3(_098_),
    .ZN(_104_)
  );
  AOI21_X1 _197_ (
    .A(_070_),
    .B1(_067_),
    .B2(_069_),
    .ZN(_105_)
  );
  OAI211_X2 _198_ (
    .A(_103_),
    .B(_104_),
    .C1(_105_),
    .C2(_091_),
    .ZN(_106_)
  );
  AND2_X2 _199_ (
    .A1(_101_),
    .A2(_106_),
    .ZN(_107_)
  );
  AOI21_X4 _200_ (
    .A(_064_),
    .B1(_084_),
    .B2(_083_),
    .ZN(_108_)
  );
  AOI21_X2 _201_ (
    .A(_075_),
    .B1(_079_),
    .B2(_080_),
    .ZN(_109_)
  );
  NOR3_X2 _202_ (
    .A1(_107_),
    .A2(_108_),
    .A3(_109_),
    .ZN(_110_)
  );
  NAND2_X2 _203_ (
    .A1(_101_),
    .A2(_106_),
    .ZN(_111_)
  );
  OAI21_X2 _204_ (
    .A(_085_),
    .B1(_076_),
    .B2(_081_),
    .ZN(_112_)
  );
  INV_X1 _205_ (
    .A(_109_),
    .ZN(_113_)
  );
  AOI21_X2 _206_ (
    .A(_111_),
    .B1(_112_),
    .B2(_113_),
    .ZN(_114_)
  );
  NOR2_X2 _207_ (
    .A1(_110_),
    .A2(_114_),
    .ZN(_115_)
  );
  AOI211_X2 _208_ (
    .A(_061_),
    .B(_088_),
    .C1(_082_),
    .C2(_086_),
    .ZN(_116_)
  );
  XNOR2_X2 _209_ (
    .A(_115_),
    .B(_116_),
    .ZN(_003_)
  );
  OAI21_X2 _210_ (
    .A(_111_),
    .B1(_108_),
    .B2(_109_),
    .ZN(_117_)
  );
  AOI21_X1 _211_ (
    .A(_061_),
    .B1(_082_),
    .B2(_086_),
    .ZN(_118_)
  );
  NAND2_X1 _212_ (
    .A1(_118_),
    .A2(_062_),
    .ZN(_119_)
  );
  OAI21_X2 _213_ (
    .A(_117_),
    .B1(_115_),
    .B2(_119_),
    .ZN(_120_)
  );
  NAND2_X2 _214_ (
    .A1(_090_),
    .A2(_092_),
    .ZN(_121_)
  );
  NAND2_X1 _215_ (
    .A1(_102_),
    .A2(_098_),
    .ZN(_122_)
  );
  NOR2_X2 _216_ (
    .A1(_093_),
    .A2(_095_),
    .ZN(_123_)
  );
  INV_X1 _217_ (
    .A(_123_),
    .ZN(_124_)
  );
  NAND2_X1 _218_ (
    .A1(_053_),
    .A2(_074_),
    .ZN(_125_)
  );
  NAND3_X1 _219_ (
    .A1(_125_),
    .A2(_066_),
    .A3(_058_),
    .ZN(_008_)
  );
  NAND2_X1 _220_ (
    .A1(_066_),
    .A2(_058_),
    .ZN(_009_)
  );
  NAND3_X1 _221_ (
    .A1(_009_),
    .A2(_053_),
    .A3(_074_),
    .ZN(_010_)
  );
  NAND2_X2 _222_ (
    .A1(_008_),
    .A2(_010_),
    .ZN(_011_)
  );
  NAND3_X2 _223_ (
    .A1(_122_),
    .A2(_124_),
    .A3(_011_),
    .ZN(_012_)
  );
  NAND2_X2 _224_ (
    .A1(_103_),
    .A2(_104_),
    .ZN(_013_)
  );
  INV_X1 _225_ (
    .A(_011_),
    .ZN(_014_)
  );
  AOI21_X2 _226_ (
    .A(_097_),
    .B1(_094_),
    .B2(_096_),
    .ZN(_015_)
  );
  OAI21_X4 _227_ (
    .A(_014_),
    .B1(_015_),
    .B2(_123_),
    .ZN(_016_)
  );
  AND4_X4 _228_ (
    .A1(_121_),
    .A2(_012_),
    .A3(_013_),
    .A4(_016_),
    .ZN(_017_)
  );
  AOI22_X4 _229_ (
    .A1(_012_),
    .A2(_016_),
    .B1(_013_),
    .B2(_121_),
    .ZN(_018_)
  );
  NOR2_X4 _230_ (
    .A1(_017_),
    .A2(_018_),
    .ZN(_019_)
  );
  XNOR2_X2 _231_ (
    .A(_120_),
    .B(_019_),
    .ZN(_004_)
  );
  NOR2_X1 _232_ (
    .A1(_019_),
    .A2(_117_),
    .ZN(_020_)
  );
  OAI21_X1 _233_ (
    .A(_107_),
    .B1(_108_),
    .B2(_109_),
    .ZN(_021_)
  );
  NAND3_X1 _234_ (
    .A1(_112_),
    .A2(_113_),
    .A3(_111_),
    .ZN(_022_)
  );
  INV_X1 _235_ (
    .A(_018_),
    .ZN(_023_)
  );
  AND2_X2 _236_ (
    .A1(_013_),
    .A2(_121_),
    .ZN(_024_)
  );
  NAND3_X2 _237_ (
    .A1(_024_),
    .A2(_012_),
    .A3(_016_),
    .ZN(_025_)
  );
  AOI22_X1 _238_ (
    .A1(_021_),
    .A2(_022_),
    .B1(_023_),
    .B2(_025_),
    .ZN(_026_)
  );
  AOI21_X2 _239_ (
    .A(_020_),
    .B1(_026_),
    .B2(_116_),
    .ZN(_027_)
  );
  NAND2_X1 _240_ (
    .A1(_012_),
    .A2(_016_),
    .ZN(_028_)
  );
  NAND2_X1 _241_ (
    .A1(_024_),
    .A2(_028_),
    .ZN(_029_)
  );
  OAI21_X1 _242_ (
    .A(_011_),
    .B1(_015_),
    .B2(_123_),
    .ZN(_030_)
  );
  NAND2_X1 _243_ (
    .A1(_029_),
    .A2(_030_),
    .ZN(_031_)
  );
  INV_X1 _244_ (
    .A(_053_),
    .ZN(_032_)
  );
  INV_X1 _245_ (
    .A(_058_),
    .ZN(_033_)
  );
  OAI211_X1 _246_ (
    .A(_066_),
    .B(_074_),
    .C1(_032_),
    .C2(_033_),
    .ZN(_034_)
  );
  XNOR2_X1 _247_ (
    .A(_031_),
    .B(_034_),
    .ZN(_035_)
  );
  XNOR2_X2 _248_ (
    .A(_027_),
    .B(_035_),
    .ZN(_005_)
  );
  INV_X1 _249_ (
    .A(_034_),
    .ZN(_036_)
  );
  NAND2_X1 _250_ (
    .A1(_031_),
    .A2(_036_),
    .ZN(_037_)
  );
  NAND4_X1 _251_ (
    .A1(_053_),
    .A2(_066_),
    .A3(_058_),
    .A4(_074_),
    .ZN(_038_)
  );
  NAND2_X1 _252_ (
    .A1(_037_),
    .A2(_038_),
    .ZN(_039_)
  );
  XNOR2_X1 _253_ (
    .A(_031_),
    .B(_036_),
    .ZN(_040_)
  );
  OAI21_X2 _254_ (
    .A(_039_),
    .B1(_027_),
    .B2(_040_),
    .ZN(_041_)
  );
  OR2_X2 _255_ (
    .A1(_019_),
    .A2(_117_),
    .ZN(_042_)
  );
  NAND2_X1 _256_ (
    .A1(_023_),
    .A2(_025_),
    .ZN(_043_)
  );
  OAI21_X1 _257_ (
    .A(_043_),
    .B1(_110_),
    .B2(_114_),
    .ZN(_044_)
  );
  OAI21_X1 _258_ (
    .A(_042_),
    .B1(_044_),
    .B2(_119_),
    .ZN(_045_)
  );
  INV_X1 _259_ (
    .A(_039_),
    .ZN(_046_)
  );
  NAND3_X1 _260_ (
    .A1(_045_),
    .A2(_035_),
    .A3(_046_),
    .ZN(_047_)
  );
  NAND2_X2 _261_ (
    .A1(_041_),
    .A2(_047_),
    .ZN(_006_)
  );
  assign a = { \fa5.cy , \add.grey6.pik , \add.black5_4.pik , \ha0.s , \add.black3_2.pik , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.a  = { \fa5.cy , \add.grey6.pik , \add.black5_4.pik , \ha0.s , \add.black3_2.pik , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.b  = { 3'h0, \fa2.cy , 2'h0, ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = 1'h0;
  assign \add.black3_2.gik  = 1'h0;
  assign \add.black3_2.gkj  = 1'h0;
  assign \add.black5_4.gij  = \add.grey5.gik ;
  assign \add.black5_4.gik  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = 1'h0;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = 1'h0;
  assign \add.g3_3  = 1'h0;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = \add.black5_4.gkj ;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = \add.grey5.gik ;
  assign \add.g5_5  = 1'h0;
  assign \add.g6_0  = \add.c6 ;
  assign \add.g6_6  = 1'h0;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = 1'h0;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gik  = 1'h0;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = \add.black5_4.gkj ;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = 1'h0;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \fa2.cy , 2'h0, ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pkj ;
  assign \fa0.sm  = \add.black3_2.pkj ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa1.h2.b ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa1.h2.s ;
  assign \fa2.c  = \fa0.cy ;
  assign \fa2.h1.b  = \fa1.h2.s ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.h2.b  = \fa0.cy ;
  assign \fa2.h2.s  = \add.black3_2.pik ;
  assign \fa2.sm  = \add.black3_2.pik ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa3.h1.b ;
  assign \fa3.c  = \fa3.h2.b ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.sm  = \fa3.h2.s ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa3.cy ;
  assign \fa4.c  = \fa4.h2.b ;
  assign \fa4.h1.b  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.h2.s  = \add.black5_4.pik ;
  assign \fa4.sm  = \add.black5_4.pik ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \fa5.a  = \fa5.h1.a ;
  assign \fa5.b  = \fa5.h1.b ;
  assign \fa5.c  = \fa4.cy ;
  assign \fa5.h2.a  = \fa5.h1.s ;
  assign \fa5.h2.b  = \fa4.cy ;
  assign \fa5.h2.s  = \add.grey6.pik ;
  assign \fa5.sm  = \add.grey6.pik ;
  assign \fa5.x  = \fa5.h1.c ;
  assign \fa5.y  = \fa5.h2.c ;
  assign \fa5.z  = \fa5.h1.s ;
  assign \ha0.a  = \fa3.h2.s ;
  assign \ha0.b  = \fa1.cy ;
  assign \ha0.c  = \fa4.h2.b ;
  assign \ha1.c  = \fa5.h1.b ;
  assign \ha1.s  = \fa4.h1.a ;
  assign ip_0_2 = \fa0.h1.a ;
  assign ip_0_3 = \fa1.h1.a ;
  assign ip_1_1 = \fa0.h1.b ;
  assign ip_1_2 = \fa1.h1.b ;
  assign ip_1_3 = \fa3.h1.a ;
  assign ip_2_0 = \fa0.h2.b ;
  assign ip_2_1 = \fa1.h2.b ;
  assign ip_2_2 = \fa3.h1.b ;
  assign ip_2_3 = \ha1.a ;
  assign ip_3_0 = \fa2.h1.a ;
  assign ip_3_1 = \fa3.h2.b ;
  assign ip_3_2 = \ha1.b ;
  assign ip_3_3 = \fa5.h1.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.cy ;
  assign p1 = \add.black3_2.pkj ;
  assign p10 = \fa5.h1.b ;
  assign p11 = \fa4.h1.a ;
  assign p12 = \fa4.cy ;
  assign p13 = \add.black5_4.pik ;
  assign p14 = \fa5.cy ;
  assign p15 = \add.grey6.pik ;
  assign p2 = \fa1.cy ;
  assign p3 = \fa1.h2.s ;
  assign p4 = \fa2.cy ;
  assign p5 = \add.black3_2.pik ;
  assign p6 = \fa3.cy ;
  assign p7 = \fa3.h2.s ;
  assign p8 = \fa4.h2.b ;
  assign p9 = \ha0.s ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _130_ = y[0];
  assign _126_ = x[0];
  assign ip_0_0 = _007_;
  assign _131_ = y[1];
  assign _132_ = y[2];
  assign _133_ = y[3];
  assign _127_ = x[1];
  assign _128_ = x[2];
  assign _129_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
