/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:3.1-62.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.13-4.14" *)
  wire _082_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.13-4.14" *)
  wire _083_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.13-4.14" *)
  wire _084_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.13-4.14" *)
  wire _085_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.15-4.16" *)
  wire _086_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.15-4.16" *)
  wire _087_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.15-4.16" *)
  wire _088_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.15-4.16" *)
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:34.12-34.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:80.13-80.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:80.15-80.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:81.14-81.15" *)
  wire [7:0] \add.s ;
  wire [5:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.7-71.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.9-71.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.11-71.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.8-72.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.11-72.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.6-73.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.8-73.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.10-73.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.7-71.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.9-71.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.11-71.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.8-72.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.11-72.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.6-73.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.8-73.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.10-73.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.7-71.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.9-71.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.11-71.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.8-72.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.11-72.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.6-73.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.8-73.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.10-73.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.7-71.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.9-71.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.11-71.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.8-72.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.11-72.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.6-73.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.8-73.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.10-73.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.7-71.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.9-71.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:71.11-71.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.8-72.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:72.11-72.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.6-73.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.8-73.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:73.10-73.11" *)
  wire \fa4.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \ha3.s ;
  (* hdlname = "ha4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.7-65.8" *)
  wire \ha4.a ;
  (* hdlname = "ha4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:65.9-65.10" *)
  wire \ha4.b ;
  (* hdlname = "ha4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.8-66.9" *)
  wire \ha4.c ;
  (* hdlname = "ha4 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:66.10-66.11" *)
  wire \ha4.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.68-7.71" *)
  wire p18;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.72-7.75" *)
  wire p19;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:35.12-35.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_87db339299c12055b99bbd2600d2d9d2.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  AND2_X1 _122_ (
    .A1(_086_),
    .A2(_082_),
    .ZN(_007_)
  );
  NAND2_X1 _123_ (
    .A1(_082_),
    .A2(_087_),
    .ZN(_008_)
  );
  NAND2_X1 _124_ (
    .A1(_086_),
    .A2(_083_),
    .ZN(_009_)
  );
  XOR2_X1 _125_ (
    .A(_008_),
    .B(_009_),
    .Z(_000_)
  );
  NAND2_X1 _126_ (
    .A1(_087_),
    .A2(_083_),
    .ZN(_010_)
  );
  NAND2_X1 _127_ (
    .A1(_082_),
    .A2(_088_),
    .ZN(_011_)
  );
  XNOR2_X1 _128_ (
    .A(_010_),
    .B(_011_),
    .ZN(_012_)
  );
  INV_X1 _129_ (
    .A(_086_),
    .ZN(_013_)
  );
  INV_X1 _130_ (
    .A(_084_),
    .ZN(_014_)
  );
  NOR2_X1 _131_ (
    .A1(_013_),
    .A2(_014_),
    .ZN(_015_)
  );
  INV_X1 _132_ (
    .A(_015_),
    .ZN(_016_)
  );
  XNOR2_X1 _133_ (
    .A(_012_),
    .B(_016_),
    .ZN(_017_)
  );
  NOR2_X1 _134_ (
    .A1(_008_),
    .A2(_009_),
    .ZN(_018_)
  );
  XNOR2_X1 _135_ (
    .A(_017_),
    .B(_018_),
    .ZN(_001_)
  );
  NAND2_X1 _136_ (
    .A1(_086_),
    .A2(_085_),
    .ZN(_019_)
  );
  NAND2_X1 _137_ (
    .A1(_087_),
    .A2(_084_),
    .ZN(_020_)
  );
  XOR2_X1 _138_ (
    .A(_019_),
    .B(_020_),
    .Z(_021_)
  );
  NAND2_X1 _139_ (
    .A1(_088_),
    .A2(_083_),
    .ZN(_022_)
  );
  NAND2_X1 _140_ (
    .A1(_082_),
    .A2(_089_),
    .ZN(_023_)
  );
  XOR2_X1 _141_ (
    .A(_022_),
    .B(_023_),
    .Z(_024_)
  );
  XNOR2_X1 _142_ (
    .A(_021_),
    .B(_024_),
    .ZN(_025_)
  );
  NOR2_X1 _143_ (
    .A1(_010_),
    .A2(_011_),
    .ZN(_026_)
  );
  INV_X1 _144_ (
    .A(_012_),
    .ZN(_027_)
  );
  AOI21_X1 _145_ (
    .A(_026_),
    .B1(_027_),
    .B2(_015_),
    .ZN(_028_)
  );
  XOR2_X1 _146_ (
    .A(_025_),
    .B(_028_),
    .Z(_029_)
  );
  INV_X1 _147_ (
    .A(_017_),
    .ZN(_030_)
  );
  NAND2_X1 _148_ (
    .A1(_030_),
    .A2(_018_),
    .ZN(_031_)
  );
  XNOR2_X1 _149_ (
    .A(_029_),
    .B(_031_),
    .ZN(_002_)
  );
  NOR2_X1 _150_ (
    .A1(_025_),
    .A2(_028_),
    .ZN(_032_)
  );
  AOI21_X1 _151_ (
    .A(_032_),
    .B1(_021_),
    .B2(_024_),
    .ZN(_033_)
  );
  INV_X1 _152_ (
    .A(_089_),
    .ZN(_034_)
  );
  INV_X1 _153_ (
    .A(_083_),
    .ZN(_035_)
  );
  NOR2_X1 _154_ (
    .A1(_034_),
    .A2(_035_),
    .ZN(_036_)
  );
  NAND2_X1 _155_ (
    .A1(_088_),
    .A2(_084_),
    .ZN(_037_)
  );
  XNOR2_X1 _156_ (
    .A(_036_),
    .B(_037_),
    .ZN(_038_)
  );
  NOR2_X1 _157_ (
    .A1(_019_),
    .A2(_020_),
    .ZN(_039_)
  );
  XNOR2_X1 _158_ (
    .A(_038_),
    .B(_039_),
    .ZN(_040_)
  );
  OR2_X1 _159_ (
    .A1(_022_),
    .A2(_023_),
    .ZN(_041_)
  );
  INV_X1 _160_ (
    .A(_087_),
    .ZN(_042_)
  );
  INV_X1 _161_ (
    .A(_085_),
    .ZN(_043_)
  );
  NOR2_X1 _162_ (
    .A1(_042_),
    .A2(_043_),
    .ZN(_044_)
  );
  XNOR2_X1 _163_ (
    .A(_041_),
    .B(_044_),
    .ZN(_045_)
  );
  XNOR2_X1 _164_ (
    .A(_040_),
    .B(_045_),
    .ZN(_046_)
  );
  XNOR2_X1 _165_ (
    .A(_033_),
    .B(_046_),
    .ZN(_047_)
  );
  NAND3_X1 _166_ (
    .A1(_029_),
    .A2(_018_),
    .A3(_030_),
    .ZN(_048_)
  );
  XNOR2_X1 _167_ (
    .A(_047_),
    .B(_048_),
    .ZN(_003_)
  );
  INV_X1 _168_ (
    .A(_033_),
    .ZN(_049_)
  );
  NAND2_X1 _169_ (
    .A1(_049_),
    .A2(_046_),
    .ZN(_050_)
  );
  INV_X1 _170_ (
    .A(_047_),
    .ZN(_051_)
  );
  OAI21_X1 _171_ (
    .A(_050_),
    .B1(_051_),
    .B2(_048_),
    .ZN(_052_)
  );
  INV_X1 _172_ (
    .A(_040_),
    .ZN(_053_)
  );
  NAND2_X1 _173_ (
    .A1(_053_),
    .A2(_045_),
    .ZN(_054_)
  );
  NAND2_X1 _174_ (
    .A1(_038_),
    .A2(_039_),
    .ZN(_055_)
  );
  NAND2_X1 _175_ (
    .A1(_054_),
    .A2(_055_),
    .ZN(_056_)
  );
  NAND2_X1 _176_ (
    .A1(_088_),
    .A2(_085_),
    .ZN(_057_)
  );
  NAND2_X1 _177_ (
    .A1(_089_),
    .A2(_084_),
    .ZN(_058_)
  );
  XNOR2_X1 _178_ (
    .A(_057_),
    .B(_058_),
    .ZN(_059_)
  );
  NOR3_X1 _179_ (
    .A1(_037_),
    .A2(_034_),
    .A3(_035_),
    .ZN(_060_)
  );
  XNOR2_X1 _180_ (
    .A(_059_),
    .B(_060_),
    .ZN(_061_)
  );
  NOR3_X1 _181_ (
    .A1(_041_),
    .A2(_042_),
    .A3(_043_),
    .ZN(_062_)
  );
  XOR2_X1 _182_ (
    .A(_061_),
    .B(_062_),
    .Z(_063_)
  );
  NAND2_X1 _183_ (
    .A1(_056_),
    .A2(_063_),
    .ZN(_064_)
  );
  INV_X1 _184_ (
    .A(_064_),
    .ZN(_065_)
  );
  NOR2_X1 _185_ (
    .A1(_056_),
    .A2(_063_),
    .ZN(_066_)
  );
  NOR2_X1 _186_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_067_)
  );
  XOR2_X1 _187_ (
    .A(_052_),
    .B(_067_),
    .Z(_004_)
  );
  NAND2_X1 _188_ (
    .A1(_067_),
    .A2(_047_),
    .ZN(_068_)
  );
  OAI221_X1 _189_ (
    .A(_064_),
    .B1(_050_),
    .B2(_066_),
    .C1(_068_),
    .C2(_048_),
    .ZN(_069_)
  );
  INV_X1 _190_ (
    .A(_060_),
    .ZN(_070_)
  );
  NOR2_X1 _191_ (
    .A1(_059_),
    .A2(_070_),
    .ZN(_071_)
  );
  NOR2_X1 _192_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(_072_)
  );
  NOR2_X1 _193_ (
    .A1(_071_),
    .A2(_072_),
    .ZN(_073_)
  );
  NOR2_X1 _194_ (
    .A1(_034_),
    .A2(_043_),
    .ZN(_074_)
  );
  XNOR2_X1 _195_ (
    .A(_073_),
    .B(_074_),
    .ZN(_075_)
  );
  NAND2_X1 _196_ (
    .A1(_061_),
    .A2(_062_),
    .ZN(_076_)
  );
  XNOR2_X1 _197_ (
    .A(_075_),
    .B(_076_),
    .ZN(_077_)
  );
  XOR2_X1 _198_ (
    .A(_069_),
    .B(_077_),
    .Z(_005_)
  );
  NAND2_X1 _199_ (
    .A1(_069_),
    .A2(_077_),
    .ZN(_078_)
  );
  NOR3_X1 _200_ (
    .A1(_073_),
    .A2(_034_),
    .A3(_043_),
    .ZN(_079_)
  );
  INV_X1 _201_ (
    .A(_076_),
    .ZN(_080_)
  );
  AOI21_X1 _202_ (
    .A(_079_),
    .B1(_075_),
    .B2(_080_),
    .ZN(_081_)
  );
  XOR2_X1 _203_ (
    .A(_078_),
    .B(_081_),
    .Z(_006_)
  );
  assign a = { \fa4.cy , \fa4.h2.s , \ha4.s , \fa2.h2.s , \fa1.h2.s , \fa0.h2.s , ip_0_1, ip_0_0 };
  assign \add.a  = { \fa4.cy , \fa4.h2.s , \ha4.s , \fa2.h2.s , \fa1.h2.s , \fa0.h2.s , ip_0_1, ip_0_0 };
  assign \add.b  = { 2'h0, \fa2.cy , \fa1.cy , 2'h0, ip_1_0, 1'h0 };
  assign \add.s [0] = ip_0_0;
  assign b = { \fa2.cy , \fa1.cy , 2'h0, ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.sm  = \fa0.h2.s ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa0.cy ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.h2.b  = \fa0.cy ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa2.h1.b ;
  assign \fa2.c  = \fa2.h2.b ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.sm  = \fa2.h2.s ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa3.h1.b ;
  assign \fa3.c  = \fa3.h2.b ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.sm  = \fa3.h2.s ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa3.cy ;
  assign \fa4.c  = \fa4.h2.b ;
  assign \fa4.h1.b  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.sm  = \fa4.h2.s ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \ha0.s  = \fa1.h1.a ;
  assign \ha1.c  = \fa2.h1.a ;
  assign \ha1.s  = \fa1.h1.b ;
  assign \ha2.c  = \fa3.h2.b ;
  assign \ha2.s  = \fa2.h1.b ;
  assign \ha3.b  = \ha0.c ;
  assign \ha3.s  = \fa2.h2.b ;
  assign \ha4.a  = \ha3.c ;
  assign \ha4.b  = \fa3.h2.s ;
  assign \ha4.c  = \fa4.h2.b ;
  assign ip_0_2 = \fa0.h1.a ;
  assign ip_0_3 = \ha0.a ;
  assign ip_1_1 = \fa0.h1.b ;
  assign ip_1_2 = \ha0.b ;
  assign ip_1_3 = \ha2.a ;
  assign ip_2_0 = \fa0.h2.b ;
  assign ip_2_1 = \ha1.a ;
  assign ip_2_2 = \ha2.b ;
  assign ip_2_3 = \fa3.h1.a ;
  assign ip_3_0 = \ha1.b ;
  assign ip_3_1 = \ha3.a ;
  assign ip_3_2 = \fa3.h1.b ;
  assign ip_3_3 = \fa4.h1.a ;
  assign o = { \add.s [7:1], ip_0_0 };
  assign p0 = \fa0.cy ;
  assign p1 = \fa0.h2.s ;
  assign p10 = \ha3.c ;
  assign p11 = \fa2.h2.b ;
  assign p12 = \fa2.cy ;
  assign p13 = \fa2.h2.s ;
  assign p14 = \fa3.cy ;
  assign p15 = \fa3.h2.s ;
  assign p16 = \fa4.h2.b ;
  assign p17 = \ha4.s ;
  assign p18 = \fa4.cy ;
  assign p19 = \fa4.h2.s ;
  assign p2 = \ha0.c ;
  assign p3 = \fa1.h1.a ;
  assign p4 = \fa2.h1.a ;
  assign p5 = \fa1.h1.b ;
  assign p6 = \fa1.cy ;
  assign p7 = \fa1.h2.s ;
  assign p8 = \fa3.h2.b ;
  assign p9 = \fa2.h1.b ;
  assign s = { \add.s [7:1], ip_0_0 };
  assign _086_ = y[0];
  assign _082_ = x[0];
  assign ip_0_0 = _007_;
  assign _087_ = y[1];
  assign _088_ = y[2];
  assign _089_ = y[3];
  assign _083_ = x[1];
  assign _084_ = x[2];
  assign _085_ = x[3];
  assign \add.s [1] = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
