/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:3.1-65.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.82-93.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.13-4.14" *)
  wire _128_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.13-4.14" *)
  wire _129_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.13-4.14" *)
  wire _130_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.13-4.14" *)
  wire _131_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.15-4.16" *)
  wire _132_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.15-4.16" *)
  wire _133_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.15-4.16" *)
  wire _134_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.15-4.16" *)
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:37.12-37.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:91.13-91.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:91.15-91.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:148.8-148.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.7-147.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.17-147.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:148.13-148.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.12-147.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.22-147.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:148.8-148.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.7-147.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.17-147.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:148.13-148.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.12-147.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:147.22-147.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.46-93.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.144-93.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.54-93.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.162-93.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.126-93.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.90-93.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.123-93.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.49-93.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.67-93.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.77-93.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:112.8-112.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.62-93.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.16-93.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.11-93.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.36-93.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:114.8-114.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.72-93.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.93-93.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.118-93.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.21-93.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:116.8-116.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.147-93.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:142.8-142.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.7-141.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.17-141.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:141.12-141.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.82-93.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.26-93.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.41-93.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.98-93.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.103-93.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.31-93.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.6-93.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:93.108-93.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:92.14-92.15" *)
  wire [7:0] \add.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:37.14-37.15" *)
  wire [7:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.7-74.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.9-74.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.11-74.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.8-75.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.11-75.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.6-76.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.8-76.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.10-76.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.7-74.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.9-74.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.11-74.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.8-75.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.11-75.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.6-76.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.8-76.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.10-76.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.7-74.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.9-74.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.11-74.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.8-75.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.11-75.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.6-76.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.8-76.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.10-76.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.7-74.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.9-74.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:74.11-74.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.8-75.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:75.11-75.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.6-76.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.8-76.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:76.10-76.11" *)
  wire \fa3.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha3.s ;
  (* hdlname = "ha4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha4.a ;
  (* hdlname = "ha4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha4.b ;
  (* hdlname = "ha4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha4.c ;
  (* hdlname = "ha4 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha4.s ;
  (* hdlname = "ha5 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha5.a ;
  (* hdlname = "ha5 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha5.b ;
  (* hdlname = "ha5 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha5.c ;
  (* hdlname = "ha5 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha5.s ;
  (* hdlname = "ha6 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha6.a ;
  (* hdlname = "ha6 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha6.b ;
  (* hdlname = "ha6 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha6.c ;
  (* hdlname = "ha6 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha6.s ;
  (* hdlname = "ha7 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha7.a ;
  (* hdlname = "ha7 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha7.b ;
  (* hdlname = "ha7 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha7.c ;
  (* hdlname = "ha7 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha7.s ;
  (* hdlname = "ha8 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.7-68.8" *)
  wire \ha8.a ;
  (* hdlname = "ha8 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:68.9-68.10" *)
  wire \ha8.b ;
  (* hdlname = "ha8 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.8-69.9" *)
  wire \ha8.c ;
  (* hdlname = "ha8 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:69.10-69.11" *)
  wire \ha8.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.68-7.71" *)
  wire p18;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.72-7.75" *)
  wire p19;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.76-7.79" *)
  wire p20;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.80-7.83" *)
  wire p21;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.84-7.87" *)
  wire p22;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.88-7.91" *)
  wire p23;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.92-7.95" *)
  wire p24;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.96-7.99" *)
  wire p25;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:38.12-38.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_c6cf4468e4c243695802c0595028a64b.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  BUF_X2 _140_ (
    .A(_128_),
    .Z(_050_)
  );
  AND2_X1 _141_ (
    .A1(_132_),
    .A2(_050_),
    .ZN(_007_)
  );
  BUF_X4 _142_ (
    .A(_129_),
    .Z(_051_)
  );
  NAND2_X1 _143_ (
    .A1(_132_),
    .A2(_051_),
    .ZN(_052_)
  );
  NAND2_X1 _144_ (
    .A1(_050_),
    .A2(_133_),
    .ZN(_053_)
  );
  XOR2_X1 _145_ (
    .A(_052_),
    .B(_053_),
    .Z(_000_)
  );
  NAND2_X1 _146_ (
    .A1(_133_),
    .A2(_051_),
    .ZN(_054_)
  );
  BUF_X4 _147_ (
    .A(_134_),
    .Z(_055_)
  );
  NAND2_X1 _148_ (
    .A1(_050_),
    .A2(_055_),
    .ZN(_056_)
  );
  XNOR2_X1 _149_ (
    .A(_054_),
    .B(_056_),
    .ZN(_057_)
  );
  BUF_X4 _150_ (
    .A(_130_),
    .Z(_058_)
  );
  AND2_X1 _151_ (
    .A1(_132_),
    .A2(_058_),
    .ZN(_059_)
  );
  XOR2_X1 _152_ (
    .A(_057_),
    .B(_059_),
    .Z(_060_)
  );
  NOR2_X1 _153_ (
    .A1(_052_),
    .A2(_053_),
    .ZN(_061_)
  );
  XNOR2_X1 _154_ (
    .A(_060_),
    .B(_061_),
    .ZN(_001_)
  );
  INV_X1 _155_ (
    .A(_057_),
    .ZN(_062_)
  );
  NAND2_X1 _156_ (
    .A1(_062_),
    .A2(_059_),
    .ZN(_063_)
  );
  INV_X1 _157_ (
    .A(_063_),
    .ZN(_064_)
  );
  INV_X1 _158_ (
    .A(_060_),
    .ZN(_065_)
  );
  AOI21_X1 _159_ (
    .A(_064_),
    .B1(_065_),
    .B2(_061_),
    .ZN(_066_)
  );
  NAND2_X1 _160_ (
    .A1(_055_),
    .A2(_051_),
    .ZN(_067_)
  );
  BUF_X4 _161_ (
    .A(_135_),
    .Z(_068_)
  );
  NAND3_X1 _162_ (
    .A1(_067_),
    .A2(_050_),
    .A3(_068_),
    .ZN(_069_)
  );
  NAND2_X1 _163_ (
    .A1(_050_),
    .A2(_068_),
    .ZN(_070_)
  );
  NAND3_X1 _164_ (
    .A1(_070_),
    .A2(_055_),
    .A3(_051_),
    .ZN(_071_)
  );
  NAND2_X1 _165_ (
    .A1(_069_),
    .A2(_071_),
    .ZN(_072_)
  );
  AND4_X4 _166_ (
    .A1(_050_),
    .A2(_133_),
    .A3(_055_),
    .A4(_051_),
    .ZN(_073_)
  );
  INV_X1 _167_ (
    .A(_073_),
    .ZN(_074_)
  );
  NAND2_X1 _168_ (
    .A1(_072_),
    .A2(_074_),
    .ZN(_075_)
  );
  NAND3_X1 _169_ (
    .A1(_069_),
    .A2(_071_),
    .A3(_073_),
    .ZN(_076_)
  );
  NAND2_X1 _170_ (
    .A1(_075_),
    .A2(_076_),
    .ZN(_077_)
  );
  BUF_X2 _171_ (
    .A(_131_),
    .Z(_078_)
  );
  NAND2_X1 _172_ (
    .A1(_132_),
    .A2(_078_),
    .ZN(_079_)
  );
  NAND2_X1 _173_ (
    .A1(_133_),
    .A2(_058_),
    .ZN(_080_)
  );
  XOR2_X2 _174_ (
    .A(_079_),
    .B(_080_),
    .Z(_081_)
  );
  INV_X1 _175_ (
    .A(_081_),
    .ZN(_082_)
  );
  NOR2_X1 _176_ (
    .A1(_077_),
    .A2(_082_),
    .ZN(_083_)
  );
  AOI21_X1 _177_ (
    .A(_081_),
    .B1(_076_),
    .B2(_075_),
    .ZN(_084_)
  );
  NOR2_X1 _178_ (
    .A1(_083_),
    .A2(_084_),
    .ZN(_085_)
  );
  INV_X2 _179_ (
    .A(_085_),
    .ZN(_086_)
  );
  XNOR2_X1 _180_ (
    .A(_066_),
    .B(_086_),
    .ZN(_002_)
  );
  NAND3_X1 _181_ (
    .A1(_086_),
    .A2(_065_),
    .A3(_061_),
    .ZN(_087_)
  );
  NAND2_X1 _182_ (
    .A1(_086_),
    .A2(_064_),
    .ZN(_088_)
  );
  NAND2_X1 _183_ (
    .A1(_087_),
    .A2(_088_),
    .ZN(_089_)
  );
  NAND4_X4 _184_ (
    .A1(_050_),
    .A2(_055_),
    .A3(_068_),
    .A4(_051_),
    .ZN(_090_)
  );
  NAND2_X1 _185_ (
    .A1(_133_),
    .A2(_078_),
    .ZN(_091_)
  );
  XNOR2_X1 _186_ (
    .A(_090_),
    .B(_091_),
    .ZN(_092_)
  );
  NOR2_X4 _187_ (
    .A1(_079_),
    .A2(_080_),
    .ZN(_093_)
  );
  NAND2_X1 _188_ (
    .A1(_055_),
    .A2(_058_),
    .ZN(_094_)
  );
  NAND3_X1 _189_ (
    .A1(_094_),
    .A2(_068_),
    .A3(_051_),
    .ZN(_095_)
  );
  NAND2_X1 _190_ (
    .A1(_068_),
    .A2(_051_),
    .ZN(_096_)
  );
  NAND3_X1 _191_ (
    .A1(_096_),
    .A2(_055_),
    .A3(_058_),
    .ZN(_097_)
  );
  NAND3_X2 _192_ (
    .A1(_093_),
    .A2(_095_),
    .A3(_097_),
    .ZN(_098_)
  );
  INV_X1 _193_ (
    .A(_098_),
    .ZN(_099_)
  );
  AOI21_X1 _194_ (
    .A(_093_),
    .B1(_095_),
    .B2(_097_),
    .ZN(_100_)
  );
  OAI21_X2 _195_ (
    .A(_092_),
    .B1(_099_),
    .B2(_100_),
    .ZN(_101_)
  );
  INV_X1 _196_ (
    .A(_091_),
    .ZN(_102_)
  );
  XNOR2_X1 _197_ (
    .A(_102_),
    .B(_090_),
    .ZN(_103_)
  );
  NAND2_X1 _198_ (
    .A1(_095_),
    .A2(_097_),
    .ZN(_104_)
  );
  INV_X1 _199_ (
    .A(_093_),
    .ZN(_105_)
  );
  NAND2_X1 _200_ (
    .A1(_104_),
    .A2(_105_),
    .ZN(_106_)
  );
  NAND3_X2 _201_ (
    .A1(_103_),
    .A2(_106_),
    .A3(_098_),
    .ZN(_107_)
  );
  NAND2_X1 _202_ (
    .A1(_101_),
    .A2(_107_),
    .ZN(_108_)
  );
  AND3_X4 _203_ (
    .A1(_069_),
    .A2(_071_),
    .A3(_073_),
    .ZN(_109_)
  );
  AOI21_X1 _204_ (
    .A(_073_),
    .B1(_069_),
    .B2(_071_),
    .ZN(_110_)
  );
  OAI21_X2 _205_ (
    .A(_081_),
    .B1(_109_),
    .B2(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _206_ (
    .A1(_072_),
    .A2(_073_),
    .ZN(_112_)
  );
  NAND2_X1 _207_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(_113_)
  );
  XNOR2_X1 _208_ (
    .A(_108_),
    .B(_113_),
    .ZN(_114_)
  );
  XNOR2_X1 _209_ (
    .A(_089_),
    .B(_114_),
    .ZN(_003_)
  );
  INV_X1 _210_ (
    .A(_114_),
    .ZN(_115_)
  );
  NAND2_X1 _211_ (
    .A1(_089_),
    .A2(_115_),
    .ZN(_116_)
  );
  NOR2_X2 _212_ (
    .A1(_090_),
    .A2(_091_),
    .ZN(_117_)
  );
  INV_X1 _213_ (
    .A(_117_),
    .ZN(_118_)
  );
  NAND2_X1 _214_ (
    .A1(_134_),
    .A2(_078_),
    .ZN(_119_)
  );
  NAND3_X1 _215_ (
    .A1(_119_),
    .A2(_068_),
    .A3(_058_),
    .ZN(_120_)
  );
  NAND2_X1 _216_ (
    .A1(_068_),
    .A2(_058_),
    .ZN(_121_)
  );
  NAND3_X2 _217_ (
    .A1(_121_),
    .A2(_055_),
    .A3(_078_),
    .ZN(_122_)
  );
  AND4_X4 _218_ (
    .A1(_134_),
    .A2(_068_),
    .A3(_051_),
    .A4(_058_),
    .ZN(_123_)
  );
  AND3_X2 _219_ (
    .A1(_120_),
    .A2(_122_),
    .A3(_123_),
    .ZN(_124_)
  );
  AOI21_X1 _220_ (
    .A(_123_),
    .B1(_120_),
    .B2(_122_),
    .ZN(_125_)
  );
  OAI21_X2 _221_ (
    .A(_118_),
    .B1(_124_),
    .B2(_125_),
    .ZN(_126_)
  );
  NAND2_X1 _222_ (
    .A1(_120_),
    .A2(_122_),
    .ZN(_127_)
  );
  INV_X1 _223_ (
    .A(_123_),
    .ZN(_008_)
  );
  NAND2_X2 _224_ (
    .A1(_127_),
    .A2(_008_),
    .ZN(_009_)
  );
  NAND3_X1 _225_ (
    .A1(_120_),
    .A2(_122_),
    .A3(_123_),
    .ZN(_010_)
  );
  NAND3_X2 _226_ (
    .A1(_009_),
    .A2(_117_),
    .A3(_010_),
    .ZN(_011_)
  );
  NAND2_X1 _227_ (
    .A1(_104_),
    .A2(_093_),
    .ZN(_012_)
  );
  INV_X1 _228_ (
    .A(_012_),
    .ZN(_013_)
  );
  AND3_X2 _229_ (
    .A1(_126_),
    .A2(_011_),
    .A3(_013_),
    .ZN(_014_)
  );
  INV_X1 _230_ (
    .A(_014_),
    .ZN(_015_)
  );
  AOI21_X2 _231_ (
    .A(_013_),
    .B1(_126_),
    .B2(_011_),
    .ZN(_016_)
  );
  INV_X1 _232_ (
    .A(_016_),
    .ZN(_017_)
  );
  AOI22_X2 _233_ (
    .A1(_101_),
    .A2(_107_),
    .B1(_111_),
    .B2(_112_),
    .ZN(_018_)
  );
  AOI21_X1 _234_ (
    .A(_092_),
    .B1(_098_),
    .B2(_106_),
    .ZN(_019_)
  );
  OAI211_X1 _235_ (
    .A(_015_),
    .B(_017_),
    .C1(_018_),
    .C2(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _236_ (
    .A1(_108_),
    .A2(_113_),
    .ZN(_021_)
  );
  INV_X1 _237_ (
    .A(_019_),
    .ZN(_022_)
  );
  OAI211_X1 _238_ (
    .A(_021_),
    .B(_022_),
    .C1(_014_),
    .C2(_016_),
    .ZN(_023_)
  );
  NAND2_X2 _239_ (
    .A1(_020_),
    .A2(_023_),
    .ZN(_024_)
  );
  XNOR2_X1 _240_ (
    .A(_116_),
    .B(_024_),
    .ZN(_004_)
  );
  OAI22_X2 _241_ (
    .A1(_018_),
    .A2(_019_),
    .B1(_014_),
    .B2(_016_),
    .ZN(_025_)
  );
  NAND2_X1 _242_ (
    .A1(_126_),
    .A2(_011_),
    .ZN(_026_)
  );
  NAND2_X1 _243_ (
    .A1(_026_),
    .A2(_013_),
    .ZN(_027_)
  );
  AOI21_X2 _244_ (
    .A(_118_),
    .B1(_009_),
    .B2(_010_),
    .ZN(_028_)
  );
  AOI21_X1 _245_ (
    .A(_008_),
    .B1(_120_),
    .B2(_122_),
    .ZN(_029_)
  );
  INV_X1 _246_ (
    .A(_055_),
    .ZN(_030_)
  );
  INV_X1 _247_ (
    .A(_058_),
    .ZN(_031_)
  );
  OAI211_X1 _248_ (
    .A(_068_),
    .B(_078_),
    .C1(_030_),
    .C2(_031_),
    .ZN(_032_)
  );
  OR3_X1 _249_ (
    .A1(_028_),
    .A2(_029_),
    .A3(_032_),
    .ZN(_033_)
  );
  OAI21_X1 _250_ (
    .A(_032_),
    .B1(_028_),
    .B2(_029_),
    .ZN(_034_)
  );
  NAND2_X1 _251_ (
    .A1(_033_),
    .A2(_034_),
    .ZN(_035_)
  );
  AND3_X2 _252_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_035_),
    .ZN(_036_)
  );
  AOI21_X2 _253_ (
    .A(_035_),
    .B1(_025_),
    .B2(_027_),
    .ZN(_037_)
  );
  NOR2_X4 _254_ (
    .A1(_036_),
    .A2(_037_),
    .ZN(_038_)
  );
  NAND3_X2 _255_ (
    .A1(_024_),
    .A2(_089_),
    .A3(_115_),
    .ZN(_039_)
  );
  XOR2_X2 _256_ (
    .A(_038_),
    .B(_039_),
    .Z(_005_)
  );
  NAND2_X1 _257_ (
    .A1(_025_),
    .A2(_027_),
    .ZN(_040_)
  );
  NAND2_X1 _258_ (
    .A1(_040_),
    .A2(_035_),
    .ZN(_041_)
  );
  OAI21_X1 _259_ (
    .A(_041_),
    .B1(_038_),
    .B2(_039_),
    .ZN(_042_)
  );
  NOR2_X1 _260_ (
    .A1(_028_),
    .A2(_029_),
    .ZN(_043_)
  );
  NOR2_X1 _261_ (
    .A1(_043_),
    .A2(_032_),
    .ZN(_044_)
  );
  NAND4_X1 _262_ (
    .A1(_055_),
    .A2(_068_),
    .A3(_058_),
    .A4(_078_),
    .ZN(_045_)
  );
  XOR2_X1 _263_ (
    .A(_044_),
    .B(_045_),
    .Z(_046_)
  );
  NAND2_X1 _264_ (
    .A1(_042_),
    .A2(_046_),
    .ZN(_047_)
  );
  INV_X1 _265_ (
    .A(_046_),
    .ZN(_048_)
  );
  OAI211_X1 _266_ (
    .A(_048_),
    .B(_041_),
    .C1(_038_),
    .C2(_039_),
    .ZN(_049_)
  );
  NAND2_X2 _267_ (
    .A1(_047_),
    .A2(_049_),
    .ZN(_006_)
  );
  assign a = { \ha7.c , \ha8.s , \add.black5_4.pik , \add.black5_4.pkj , \add.black3_2.pik , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.a  = { \ha7.c , \ha8.s , \add.black5_4.pik , \add.black5_4.pkj , \add.black3_2.pik , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.b  = { \ha8.c , \fa3.cy , 3'h0, \ha0.s , ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = \add.grey3.gik ;
  assign \add.black3_2.gik  = 1'h0;
  assign \add.black5_4.gij  = 1'h0;
  assign \add.black5_4.gik  = 1'h0;
  assign \add.black5_4.gkj  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = \add.black3_2.gkj ;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = \add.grey3.gik ;
  assign \add.g3_3  = 1'h0;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = 1'h0;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = 1'h0;
  assign \add.g5_5  = 1'h0;
  assign \add.g6_0  = \add.c6 ;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = \add.black3_2.gkj ;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = 1'h0;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gik  = 1'h0;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = \add.g6_6 ;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \ha8.c , \fa3.cy , 3'h0, \ha0.s , ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pik ;
  assign \fa0.sm  = \add.black3_2.pik ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa0.cy ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.h2.b  = \fa0.cy ;
  assign \fa1.h2.s  = \add.black5_4.pkj ;
  assign \fa1.sm  = \add.black5_4.pkj ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa2.h1.b ;
  assign \fa2.c  = \fa2.h2.b ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.sm  = \fa2.h2.s ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa2.h2.s ;
  assign \fa3.c  = \fa1.cy ;
  assign \fa3.h1.b  = \fa2.h2.s ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.h2.b  = \fa1.cy ;
  assign \fa3.h2.s  = \add.black5_4.pik ;
  assign \fa3.sm  = \add.black5_4.pik ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \ha0.c  = \fa0.h1.a ;
  assign \ha1.s  = \fa0.h1.b ;
  assign \ha2.s  = \fa0.h2.b ;
  assign \ha3.c  = \fa2.h1.b ;
  assign \ha4.b  = \ha1.c ;
  assign \ha4.c  = \fa2.h2.b ;
  assign \ha4.s  = \fa1.h1.a ;
  assign \ha5.a  = \ha2.c ;
  assign \ha5.b  = \ha3.s ;
  assign \ha5.c  = \fa3.h1.a ;
  assign \ha5.s  = \fa1.h1.b ;
  assign \ha6.s  = \fa2.h1.a ;
  assign \ha7.b  = \ha6.c ;
  assign \ha8.a  = \ha7.s ;
  assign \ha8.b  = \fa2.cy ;
  assign ip_0_2 = \ha0.a ;
  assign ip_0_3 = \ha1.a ;
  assign ip_1_1 = \ha0.b ;
  assign ip_1_2 = \ha1.b ;
  assign ip_1_3 = \ha3.a ;
  assign ip_2_1 = \ha2.a ;
  assign ip_2_2 = \ha3.b ;
  assign ip_2_3 = \ha6.a ;
  assign ip_3_0 = \ha2.b ;
  assign ip_3_1 = \ha4.a ;
  assign ip_3_2 = \ha6.b ;
  assign ip_3_3 = \ha7.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.h1.a ;
  assign p1 = \ha0.s ;
  assign p10 = \fa2.h2.b ;
  assign p11 = \fa1.h1.a ;
  assign p12 = \fa3.h1.a ;
  assign p13 = \fa1.h1.b ;
  assign p14 = \fa1.cy ;
  assign p15 = \add.black5_4.pkj ;
  assign p16 = \ha6.c ;
  assign p17 = \fa2.h1.a ;
  assign p18 = \fa2.cy ;
  assign p19 = \fa2.h2.s ;
  assign p2 = \ha1.c ;
  assign p20 = \fa3.cy ;
  assign p21 = \add.black5_4.pik ;
  assign p22 = \ha7.c ;
  assign p23 = \ha7.s ;
  assign p24 = \ha8.c ;
  assign p25 = \ha8.s ;
  assign p3 = \fa0.h1.b ;
  assign p4 = \ha2.c ;
  assign p5 = \fa0.h2.b ;
  assign p6 = \fa0.cy ;
  assign p7 = \add.black3_2.pik ;
  assign p8 = \fa2.h1.b ;
  assign p9 = \ha3.s ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _132_ = y[0];
  assign _128_ = x[0];
  assign ip_0_0 = _007_;
  assign _133_ = y[1];
  assign _134_ = y[2];
  assign _135_ = y[3];
  assign _129_ = x[1];
  assign _130_ = x[2];
  assign _131_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
