/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:3.1-64.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.82-92.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.13-4.14" *)
  wire _138_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.13-4.14" *)
  wire _139_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.13-4.14" *)
  wire _140_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.13-4.14" *)
  wire _141_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.15-4.16" *)
  wire _142_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.15-4.16" *)
  wire _143_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.15-4.16" *)
  wire _144_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.15-4.16" *)
  wire _145_;
  wire _146_;
  wire _147_;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:36.12-36.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:90.13-90.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:90.15-90.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:147.8-147.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.7-146.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.17-146.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:147.13-147.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.12-146.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.22-146.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:147.8-147.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.7-146.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.17-146.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:147.13-147.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.12-146.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:146.22-146.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.46-92.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.144-92.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.54-92.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.162-92.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.126-92.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.90-92.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.123-92.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.49-92.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.67-92.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.77-92.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:111.8-111.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.62-92.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.16-92.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.11-92.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.36-92.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:113.8-113.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.72-92.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.93-92.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.118-92.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.21-92.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:115.8-115.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.147-92.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:141.8-141.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.7-140.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.17-140.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:140.12-140.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.82-92.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.26-92.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.41-92.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.98-92.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.103-92.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.31-92.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.6-92.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:92.108-92.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:91.14-91.15" *)
  wire [7:0] \add.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:36.14-36.15" *)
  wire [7:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.7-73.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.9-73.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.11-73.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.8-74.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.11-74.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.6-75.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.8-75.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.10-75.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.7-73.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.9-73.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.11-73.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.8-74.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.11-74.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.6-75.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.8-75.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.10-75.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.7-73.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.9-73.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.11-73.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.8-74.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.11-74.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.6-75.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.8-75.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.10-75.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.7-73.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.9-73.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.11-73.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.8-74.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.11-74.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.6-75.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.8-75.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.10-75.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.7-73.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.9-73.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:73.11-73.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.8-74.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:74.11-74.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.6-75.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.8-75.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:75.10-75.11" *)
  wire \fa4.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha3.s ;
  (* hdlname = "ha4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha4.a ;
  (* hdlname = "ha4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha4.b ;
  (* hdlname = "ha4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha4.c ;
  (* hdlname = "ha4 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha4.s ;
  (* hdlname = "ha5 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha5.a ;
  (* hdlname = "ha5 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha5.b ;
  (* hdlname = "ha5 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha5.c ;
  (* hdlname = "ha5 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha5.s ;
  (* hdlname = "ha6 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.7-67.8" *)
  wire \ha6.a ;
  (* hdlname = "ha6 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:67.9-67.10" *)
  wire \ha6.b ;
  (* hdlname = "ha6 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.8-68.9" *)
  wire \ha6.c ;
  (* hdlname = "ha6 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:68.10-68.11" *)
  wire \ha6.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.68-7.71" *)
  wire p18;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.72-7.75" *)
  wire p19;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.76-7.79" *)
  wire p20;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.80-7.83" *)
  wire p21;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.84-7.87" *)
  wire p22;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.88-7.91" *)
  wire p23;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:37.12-37.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_cfb234a06070bd92a01c5f13d5f4e35e.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  BUF_X2 _148_ (
    .A(_142_),
    .Z(_060_)
  );
  BUF_X2 _149_ (
    .A(_138_),
    .Z(_061_)
  );
  AND2_X1 _150_ (
    .A1(_060_),
    .A2(_061_),
    .ZN(_007_)
  );
  BUF_X4 _151_ (
    .A(_139_),
    .Z(_062_)
  );
  NAND2_X1 _152_ (
    .A1(_060_),
    .A2(_062_),
    .ZN(_063_)
  );
  BUF_X2 _153_ (
    .A(_143_),
    .Z(_064_)
  );
  NAND2_X1 _154_ (
    .A1(_061_),
    .A2(_064_),
    .ZN(_065_)
  );
  XOR2_X1 _155_ (
    .A(_063_),
    .B(_065_),
    .Z(_000_)
  );
  AND2_X2 _156_ (
    .A1(_064_),
    .A2(_062_),
    .ZN(_066_)
  );
  BUF_X4 _157_ (
    .A(_144_),
    .Z(_067_)
  );
  NAND2_X1 _158_ (
    .A1(_061_),
    .A2(_067_),
    .ZN(_068_)
  );
  XNOR2_X1 _159_ (
    .A(_066_),
    .B(_068_),
    .ZN(_069_)
  );
  BUF_X4 _160_ (
    .A(_140_),
    .Z(_070_)
  );
  NAND2_X1 _161_ (
    .A1(_060_),
    .A2(_070_),
    .ZN(_071_)
  );
  INV_X1 _162_ (
    .A(_071_),
    .ZN(_072_)
  );
  XNOR2_X1 _163_ (
    .A(_069_),
    .B(_072_),
    .ZN(_073_)
  );
  NOR2_X1 _164_ (
    .A1(_063_),
    .A2(_065_),
    .ZN(_074_)
  );
  XNOR2_X1 _165_ (
    .A(_073_),
    .B(_074_),
    .ZN(_001_)
  );
  NAND2_X1 _166_ (
    .A1(_144_),
    .A2(_062_),
    .ZN(_075_)
  );
  BUF_X4 _167_ (
    .A(_145_),
    .Z(_076_)
  );
  NAND3_X1 _168_ (
    .A1(_075_),
    .A2(_061_),
    .A3(_076_),
    .ZN(_077_)
  );
  NAND2_X1 _169_ (
    .A1(_061_),
    .A2(_076_),
    .ZN(_078_)
  );
  NAND3_X1 _170_ (
    .A1(_078_),
    .A2(_067_),
    .A3(_062_),
    .ZN(_079_)
  );
  NAND2_X2 _171_ (
    .A1(_077_),
    .A2(_079_),
    .ZN(_080_)
  );
  BUF_X4 _172_ (
    .A(_141_),
    .Z(_081_)
  );
  NAND2_X1 _173_ (
    .A1(_060_),
    .A2(_081_),
    .ZN(_082_)
  );
  NAND3_X1 _174_ (
    .A1(_082_),
    .A2(_064_),
    .A3(_070_),
    .ZN(_083_)
  );
  NAND2_X1 _175_ (
    .A1(_064_),
    .A2(_070_),
    .ZN(_084_)
  );
  NAND3_X1 _176_ (
    .A1(_084_),
    .A2(_060_),
    .A3(_081_),
    .ZN(_085_)
  );
  NAND3_X1 _177_ (
    .A1(_080_),
    .A2(_083_),
    .A3(_085_),
    .ZN(_086_)
  );
  NAND2_X1 _178_ (
    .A1(_083_),
    .A2(_085_),
    .ZN(_087_)
  );
  NAND3_X1 _179_ (
    .A1(_087_),
    .A2(_077_),
    .A3(_079_),
    .ZN(_088_)
  );
  NAND2_X1 _180_ (
    .A1(_086_),
    .A2(_088_),
    .ZN(_089_)
  );
  AND4_X1 _181_ (
    .A1(_061_),
    .A2(_064_),
    .A3(_067_),
    .A4(_062_),
    .ZN(_090_)
  );
  AOI21_X1 _182_ (
    .A(_090_),
    .B1(_069_),
    .B2(_072_),
    .ZN(_091_)
  );
  AND2_X1 _183_ (
    .A1(_089_),
    .A2(_091_),
    .ZN(_092_)
  );
  NOR2_X1 _184_ (
    .A1(_089_),
    .A2(_091_),
    .ZN(_093_)
  );
  NOR2_X1 _185_ (
    .A1(_092_),
    .A2(_093_),
    .ZN(_094_)
  );
  INV_X1 _186_ (
    .A(_073_),
    .ZN(_095_)
  );
  NAND2_X1 _187_ (
    .A1(_095_),
    .A2(_074_),
    .ZN(_096_)
  );
  XOR2_X1 _188_ (
    .A(_094_),
    .B(_096_),
    .Z(_002_)
  );
  OAI211_X1 _189_ (
    .A(_095_),
    .B(_074_),
    .C1(_092_),
    .C2(_093_),
    .ZN(_097_)
  );
  INV_X1 _190_ (
    .A(_089_),
    .ZN(_098_)
  );
  OR2_X1 _191_ (
    .A1(_098_),
    .A2(_091_),
    .ZN(_099_)
  );
  NAND2_X2 _192_ (
    .A1(_097_),
    .A2(_099_),
    .ZN(_100_)
  );
  NAND4_X4 _193_ (
    .A1(_060_),
    .A2(_064_),
    .A3(_070_),
    .A4(_081_),
    .ZN(_101_)
  );
  NAND2_X2 _194_ (
    .A1(_064_),
    .A2(_081_),
    .ZN(_102_)
  );
  AND2_X4 _195_ (
    .A1(_067_),
    .A2(_062_),
    .ZN(_103_)
  );
  AND2_X4 _196_ (
    .A1(_061_),
    .A2(_076_),
    .ZN(_104_)
  );
  AOI21_X2 _197_ (
    .A(_102_),
    .B1(_103_),
    .B2(_104_),
    .ZN(_105_)
  );
  NAND4_X4 _198_ (
    .A1(_061_),
    .A2(_067_),
    .A3(_076_),
    .A4(_062_),
    .ZN(_106_)
  );
  AND2_X2 _199_ (
    .A1(_064_),
    .A2(_081_),
    .ZN(_107_)
  );
  NOR2_X2 _200_ (
    .A1(_106_),
    .A2(_107_),
    .ZN(_108_)
  );
  OAI21_X4 _201_ (
    .A(_101_),
    .B1(_105_),
    .B2(_108_),
    .ZN(_109_)
  );
  NAND3_X4 _202_ (
    .A1(_103_),
    .A2(_104_),
    .A3(_102_),
    .ZN(_110_)
  );
  NAND2_X2 _203_ (
    .A1(_106_),
    .A2(_107_),
    .ZN(_111_)
  );
  INV_X1 _204_ (
    .A(_101_),
    .ZN(_112_)
  );
  NAND3_X4 _205_ (
    .A1(_110_),
    .A2(_111_),
    .A3(_112_),
    .ZN(_113_)
  );
  NAND2_X2 _206_ (
    .A1(_067_),
    .A2(_070_),
    .ZN(_114_)
  );
  NAND2_X1 _207_ (
    .A1(_076_),
    .A2(_062_),
    .ZN(_115_)
  );
  XNOR2_X2 _208_ (
    .A(_114_),
    .B(_115_),
    .ZN(_116_)
  );
  AND3_X1 _209_ (
    .A1(_116_),
    .A2(_087_),
    .A3(_080_),
    .ZN(_117_)
  );
  NAND3_X1 _210_ (
    .A1(_114_),
    .A2(_076_),
    .A3(_062_),
    .ZN(_118_)
  );
  NAND3_X1 _211_ (
    .A1(_115_),
    .A2(_067_),
    .A3(_070_),
    .ZN(_119_)
  );
  AOI22_X1 _212_ (
    .A1(_087_),
    .A2(_080_),
    .B1(_118_),
    .B2(_119_),
    .ZN(_120_)
  );
  OAI211_X1 _213_ (
    .A(_109_),
    .B(_113_),
    .C1(_117_),
    .C2(_120_),
    .ZN(_121_)
  );
  NAND2_X2 _214_ (
    .A1(_109_),
    .A2(_113_),
    .ZN(_122_)
  );
  NAND2_X1 _215_ (
    .A1(_087_),
    .A2(_080_),
    .ZN(_123_)
  );
  NAND2_X1 _216_ (
    .A1(_118_),
    .A2(_119_),
    .ZN(_124_)
  );
  NAND2_X1 _217_ (
    .A1(_123_),
    .A2(_124_),
    .ZN(_125_)
  );
  NAND3_X1 _218_ (
    .A1(_116_),
    .A2(_087_),
    .A3(_080_),
    .ZN(_126_)
  );
  NAND3_X1 _219_ (
    .A1(_122_),
    .A2(_125_),
    .A3(_126_),
    .ZN(_127_)
  );
  NAND2_X1 _220_ (
    .A1(_121_),
    .A2(_127_),
    .ZN(_128_)
  );
  XOR2_X1 _221_ (
    .A(_100_),
    .B(_128_),
    .Z(_003_)
  );
  NAND2_X1 _222_ (
    .A1(_100_),
    .A2(_128_),
    .ZN(_129_)
  );
  OAI21_X2 _223_ (
    .A(_112_),
    .B1(_105_),
    .B2(_108_),
    .ZN(_130_)
  );
  NOR2_X2 _224_ (
    .A1(_106_),
    .A2(_102_),
    .ZN(_131_)
  );
  INV_X1 _225_ (
    .A(_131_),
    .ZN(_132_)
  );
  AND4_X2 _226_ (
    .A1(_144_),
    .A2(_145_),
    .A3(_062_),
    .A4(_070_),
    .ZN(_133_)
  );
  NAND2_X1 _227_ (
    .A1(_067_),
    .A2(_081_),
    .ZN(_134_)
  );
  NAND3_X2 _228_ (
    .A1(_134_),
    .A2(_076_),
    .A3(_070_),
    .ZN(_135_)
  );
  NAND2_X1 _229_ (
    .A1(_076_),
    .A2(_070_),
    .ZN(_136_)
  );
  NAND3_X2 _230_ (
    .A1(_136_),
    .A2(_067_),
    .A3(_081_),
    .ZN(_137_)
  );
  AOI21_X2 _231_ (
    .A(_133_),
    .B1(_135_),
    .B2(_137_),
    .ZN(_008_)
  );
  AND3_X4 _232_ (
    .A1(_135_),
    .A2(_137_),
    .A3(_133_),
    .ZN(_009_)
  );
  OAI211_X4 _233_ (
    .A(_130_),
    .B(_132_),
    .C1(_008_),
    .C2(_009_),
    .ZN(_010_)
  );
  NAND2_X1 _234_ (
    .A1(_135_),
    .A2(_137_),
    .ZN(_011_)
  );
  INV_X1 _235_ (
    .A(_133_),
    .ZN(_012_)
  );
  NAND2_X2 _236_ (
    .A1(_011_),
    .A2(_012_),
    .ZN(_013_)
  );
  NAND3_X1 _237_ (
    .A1(_135_),
    .A2(_137_),
    .A3(_133_),
    .ZN(_014_)
  );
  AOI21_X4 _238_ (
    .A(_101_),
    .B1(_110_),
    .B2(_111_),
    .ZN(_015_)
  );
  OAI211_X4 _239_ (
    .A(_013_),
    .B(_014_),
    .C1(_015_),
    .C2(_131_),
    .ZN(_016_)
  );
  AOI22_X4 _240_ (
    .A1(_125_),
    .A2(_126_),
    .B1(_109_),
    .B2(_113_),
    .ZN(_017_)
  );
  NOR2_X2 _241_ (
    .A1(_123_),
    .A2(_116_),
    .ZN(_018_)
  );
  OAI211_X2 _242_ (
    .A(_010_),
    .B(_016_),
    .C1(_017_),
    .C2(_018_),
    .ZN(_019_)
  );
  NAND2_X4 _243_ (
    .A1(_010_),
    .A2(_016_),
    .ZN(_020_)
  );
  OAI21_X2 _244_ (
    .A(_122_),
    .B1(_117_),
    .B2(_120_),
    .ZN(_021_)
  );
  INV_X1 _245_ (
    .A(_018_),
    .ZN(_022_)
  );
  NAND3_X2 _246_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_022_),
    .ZN(_023_)
  );
  NAND2_X1 _247_ (
    .A1(_019_),
    .A2(_023_),
    .ZN(_024_)
  );
  XNOR2_X1 _248_ (
    .A(_129_),
    .B(_024_),
    .ZN(_004_)
  );
  AOI22_X2 _249_ (
    .A1(_019_),
    .A2(_023_),
    .B1(_121_),
    .B2(_127_),
    .ZN(_025_)
  );
  NAND2_X1 _250_ (
    .A1(_025_),
    .A2(_100_),
    .ZN(_026_)
  );
  NAND2_X1 _251_ (
    .A1(_011_),
    .A2(_133_),
    .ZN(_027_)
  );
  INV_X1 _252_ (
    .A(_067_),
    .ZN(_028_)
  );
  INV_X1 _253_ (
    .A(_070_),
    .ZN(_029_)
  );
  OAI211_X1 _254_ (
    .A(_076_),
    .B(_081_),
    .C1(_028_),
    .C2(_029_),
    .ZN(_030_)
  );
  XNOR2_X1 _255_ (
    .A(_027_),
    .B(_030_),
    .ZN(_031_)
  );
  AOI22_X2 _256_ (
    .A1(_021_),
    .A2(_022_),
    .B1(_010_),
    .B2(_016_),
    .ZN(_032_)
  );
  NOR2_X1 _257_ (
    .A1(_015_),
    .A2(_131_),
    .ZN(_033_)
  );
  NOR2_X1 _258_ (
    .A1(_009_),
    .A2(_008_),
    .ZN(_034_)
  );
  NOR2_X2 _259_ (
    .A1(_033_),
    .A2(_034_),
    .ZN(_035_)
  );
  OAI21_X1 _260_ (
    .A(_031_),
    .B1(_032_),
    .B2(_035_),
    .ZN(_036_)
  );
  OAI21_X2 _261_ (
    .A(_020_),
    .B1(_017_),
    .B2(_018_),
    .ZN(_037_)
  );
  INV_X1 _262_ (
    .A(_035_),
    .ZN(_038_)
  );
  INV_X1 _263_ (
    .A(_031_),
    .ZN(_039_)
  );
  NAND3_X1 _264_ (
    .A1(_037_),
    .A2(_038_),
    .A3(_039_),
    .ZN(_040_)
  );
  NAND2_X2 _265_ (
    .A1(_036_),
    .A2(_040_),
    .ZN(_041_)
  );
  XNOR2_X2 _266_ (
    .A(_026_),
    .B(_041_),
    .ZN(_005_)
  );
  NOR3_X1 _267_ (
    .A1(_032_),
    .A2(_035_),
    .A3(_031_),
    .ZN(_042_)
  );
  AOI21_X1 _268_ (
    .A(_039_),
    .B1(_037_),
    .B2(_038_),
    .ZN(_043_)
  );
  OAI211_X1 _269_ (
    .A(_025_),
    .B(_100_),
    .C1(_042_),
    .C2(_043_),
    .ZN(_044_)
  );
  AOI21_X1 _270_ (
    .A(_031_),
    .B1(_037_),
    .B2(_038_),
    .ZN(_045_)
  );
  NOR2_X1 _271_ (
    .A1(_027_),
    .A2(_030_),
    .ZN(_046_)
  );
  NOR2_X1 _272_ (
    .A1(_134_),
    .A2(_136_),
    .ZN(_047_)
  );
  AND2_X1 _273_ (
    .A1(_076_),
    .A2(_081_),
    .ZN(_048_)
  );
  NAND2_X1 _274_ (
    .A1(_047_),
    .A2(_048_),
    .ZN(_049_)
  );
  NOR3_X1 _275_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_049_),
    .ZN(_050_)
  );
  INV_X1 _276_ (
    .A(_049_),
    .ZN(_051_)
  );
  OAI21_X1 _277_ (
    .A(_039_),
    .B1(_032_),
    .B2(_035_),
    .ZN(_052_)
  );
  INV_X1 _278_ (
    .A(_046_),
    .ZN(_053_)
  );
  AOI21_X1 _279_ (
    .A(_051_),
    .B1(_052_),
    .B2(_053_),
    .ZN(_054_)
  );
  OAI21_X2 _280_ (
    .A(_044_),
    .B1(_050_),
    .B2(_054_),
    .ZN(_055_)
  );
  AND3_X2 _281_ (
    .A1(_100_),
    .A2(_024_),
    .A3(_128_),
    .ZN(_056_)
  );
  OAI21_X2 _282_ (
    .A(_049_),
    .B1(_045_),
    .B2(_046_),
    .ZN(_057_)
  );
  NAND3_X1 _283_ (
    .A1(_052_),
    .A2(_053_),
    .A3(_051_),
    .ZN(_058_)
  );
  NAND4_X4 _284_ (
    .A1(_056_),
    .A2(_057_),
    .A3(_041_),
    .A4(_058_),
    .ZN(_059_)
  );
  NAND2_X4 _285_ (
    .A1(_055_),
    .A2(_059_),
    .ZN(_006_)
  );
  assign a = { \ha6.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \ha2.s , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.a  = { \ha6.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \ha2.s , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.b  = { \fa4.cy , 3'h0, \fa0.cy , 1'h0, ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = \add.g3_3 ;
  assign \add.black3_2.gik  = \add.g3_3 ;
  assign \add.black3_2.gkj  = 1'h0;
  assign \add.black5_4.gij  = 1'h0;
  assign \add.black5_4.gik  = 1'h0;
  assign \add.black5_4.gkj  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = 1'h0;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = \add.g3_3 ;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = 1'h0;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = 1'h0;
  assign \add.g5_5  = 1'h0;
  assign \add.g6_0  = \add.c6 ;
  assign \add.g6_6  = 1'h0;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = 1'h0;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gik  = \add.g3_3 ;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = 1'h0;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gik  = 1'h0;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = 1'h0;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \fa4.cy , 3'h0, \fa0.cy , 1'h0, ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pkj ;
  assign \fa0.sm  = \add.black3_2.pkj ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa1.h2.b ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa2.h1.b ;
  assign \fa2.c  = \fa1.h2.s ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.h2.b  = \fa1.h2.s ;
  assign \fa2.h2.s  = \add.black5_4.pkj ;
  assign \fa2.sm  = \add.black5_4.pkj ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa1.cy ;
  assign \fa3.c  = \fa2.cy ;
  assign \fa3.h1.b  = \fa1.cy ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.h2.b  = \fa2.cy ;
  assign \fa3.h2.s  = \add.black5_4.pik ;
  assign \fa3.sm  = \add.black5_4.pik ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa4.h1.b ;
  assign \fa4.c  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.h2.b  = \fa3.cy ;
  assign \fa4.h2.s  = \add.grey6.pik ;
  assign \fa4.sm  = \add.grey6.pik ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \ha0.c  = \fa1.h1.b ;
  assign \ha1.c  = \fa1.h2.b ;
  assign \ha2.a  = \ha0.s ;
  assign \ha2.b  = \ha1.s ;
  assign \ha2.c  = \fa2.h1.b ;
  assign \ha3.s  = \fa2.h1.a ;
  assign \ha5.a  = \ha4.s ;
  assign \ha5.b  = \ha3.c ;
  assign \ha5.c  = \fa4.h1.a ;
  assign \ha5.s  = \fa3.h1.a ;
  assign \ha6.b  = \ha4.c ;
  assign \ha6.s  = \fa4.h1.b ;
  assign ip_0_2 = \fa0.h1.a ;
  assign ip_0_3 = \ha0.a ;
  assign ip_1_1 = \fa0.h1.b ;
  assign ip_1_2 = \ha0.b ;
  assign ip_1_3 = \ha3.a ;
  assign ip_2_0 = \fa0.h2.b ;
  assign ip_2_1 = \ha1.a ;
  assign ip_2_2 = \ha3.b ;
  assign ip_2_3 = \ha4.a ;
  assign ip_3_0 = \ha1.b ;
  assign ip_3_1 = \fa1.h1.a ;
  assign ip_3_2 = \ha4.b ;
  assign ip_3_3 = \ha6.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.cy ;
  assign p1 = \add.black3_2.pkj ;
  assign p10 = \fa1.cy ;
  assign p11 = \fa1.h2.s ;
  assign p12 = \fa2.cy ;
  assign p13 = \add.black5_4.pkj ;
  assign p14 = \ha4.c ;
  assign p15 = \ha4.s ;
  assign p16 = \fa4.h1.a ;
  assign p17 = \fa3.h1.a ;
  assign p18 = \fa3.cy ;
  assign p19 = \add.black5_4.pik ;
  assign p2 = \fa1.h1.b ;
  assign p20 = \ha6.c ;
  assign p21 = \fa4.h1.b ;
  assign p22 = \fa4.cy ;
  assign p23 = \add.grey6.pik ;
  assign p3 = \ha0.s ;
  assign p4 = \fa1.h2.b ;
  assign p5 = \ha1.s ;
  assign p6 = \fa2.h1.b ;
  assign p7 = \ha2.s ;
  assign p8 = \ha3.c ;
  assign p9 = \fa2.h1.a ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _142_ = y[0];
  assign _138_ = x[0];
  assign ip_0_0 = _007_;
  assign _143_ = y[1];
  assign _144_ = y[2];
  assign _145_ = y[3];
  assign _139_ = x[1];
  assign _140_ = x[2];
  assign _141_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
