/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:3.1-59.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.13-4.14" *)
  wire _112_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.13-4.14" *)
  wire _113_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.13-4.14" *)
  wire _114_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.13-4.14" *)
  wire _115_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.15-4.16" *)
  wire _116_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.15-4.16" *)
  wire _117_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.15-4.16" *)
  wire _118_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.15-4.16" *)
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:31.12-31.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:77.13-77.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:77.15-77.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:78.14-78.15" *)
  wire [7:0] \add.s ;
  wire [5:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.7-68.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.9-68.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.11-68.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.8-69.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.11-69.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.6-70.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.8-70.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.10-70.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.7-68.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.9-68.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.11-68.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.8-69.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.11-69.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.6-70.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.8-70.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.10-70.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.7-68.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.9-68.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:68.11-68.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.8-69.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:69.11-69.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.6-70.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.8-70.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:70.10-70.11" *)
  wire \fa2.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.7-62.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:62.9-62.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.8-63.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:63.10-63.11" *)
  wire \ha3.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:32.12-32.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_5125c5ea660e70dd292ebf5a62b53928.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  INV_X1 _152_ (
    .A(_116_),
    .ZN(_034_)
  );
  BUF_X4 _153_ (
    .A(_112_),
    .Z(_035_)
  );
  INV_X1 _154_ (
    .A(_035_),
    .ZN(_036_)
  );
  NOR2_X1 _155_ (
    .A1(_034_),
    .A2(_036_),
    .ZN(_007_)
  );
  BUF_X4 _156_ (
    .A(_117_),
    .Z(_037_)
  );
  NAND2_X1 _157_ (
    .A1(_035_),
    .A2(_037_),
    .ZN(_038_)
  );
  BUF_X4 _158_ (
    .A(_113_),
    .Z(_039_)
  );
  NAND2_X1 _159_ (
    .A1(_116_),
    .A2(_039_),
    .ZN(_040_)
  );
  XOR2_X1 _160_ (
    .A(_038_),
    .B(_040_),
    .Z(_000_)
  );
  NAND2_X1 _161_ (
    .A1(_037_),
    .A2(_039_),
    .ZN(_041_)
  );
  BUF_X4 _162_ (
    .A(_118_),
    .Z(_042_)
  );
  NAND3_X1 _163_ (
    .A1(_041_),
    .A2(_035_),
    .A3(_042_),
    .ZN(_043_)
  );
  NAND2_X1 _164_ (
    .A1(_035_),
    .A2(_042_),
    .ZN(_044_)
  );
  NAND3_X1 _165_ (
    .A1(_044_),
    .A2(_037_),
    .A3(_039_),
    .ZN(_045_)
  );
  BUF_X4 _166_ (
    .A(_114_),
    .Z(_046_)
  );
  NAND2_X1 _167_ (
    .A1(_116_),
    .A2(_046_),
    .ZN(_047_)
  );
  AND3_X1 _168_ (
    .A1(_043_),
    .A2(_045_),
    .A3(_047_),
    .ZN(_048_)
  );
  AOI21_X1 _169_ (
    .A(_047_),
    .B1(_043_),
    .B2(_045_),
    .ZN(_049_)
  );
  NOR2_X1 _170_ (
    .A1(_048_),
    .A2(_049_),
    .ZN(_050_)
  );
  NOR2_X1 _171_ (
    .A1(_038_),
    .A2(_040_),
    .ZN(_051_)
  );
  INV_X1 _172_ (
    .A(_051_),
    .ZN(_052_)
  );
  XNOR2_X1 _173_ (
    .A(_050_),
    .B(_052_),
    .ZN(_001_)
  );
  NAND2_X1 _174_ (
    .A1(_037_),
    .A2(_046_),
    .ZN(_053_)
  );
  INV_X1 _175_ (
    .A(_053_),
    .ZN(_054_)
  );
  NAND2_X1 _176_ (
    .A1(_042_),
    .A2(_039_),
    .ZN(_055_)
  );
  BUF_X4 _177_ (
    .A(_119_),
    .Z(_056_)
  );
  NAND3_X1 _178_ (
    .A1(_055_),
    .A2(_035_),
    .A3(_056_),
    .ZN(_057_)
  );
  NAND2_X1 _179_ (
    .A1(_035_),
    .A2(_056_),
    .ZN(_058_)
  );
  NAND3_X1 _180_ (
    .A1(_058_),
    .A2(_042_),
    .A3(_039_),
    .ZN(_059_)
  );
  AOI21_X2 _181_ (
    .A(_054_),
    .B1(_057_),
    .B2(_059_),
    .ZN(_060_)
  );
  INV_X1 _182_ (
    .A(_060_),
    .ZN(_061_)
  );
  NAND3_X1 _183_ (
    .A1(_057_),
    .A2(_059_),
    .A3(_054_),
    .ZN(_062_)
  );
  NAND4_X4 _184_ (
    .A1(_035_),
    .A2(_037_),
    .A3(_042_),
    .A4(_039_),
    .ZN(_063_)
  );
  NAND2_X1 _185_ (
    .A1(_116_),
    .A2(_115_),
    .ZN(_064_)
  );
  XNOR2_X1 _186_ (
    .A(_063_),
    .B(_064_),
    .ZN(_065_)
  );
  NAND3_X1 _187_ (
    .A1(_061_),
    .A2(_062_),
    .A3(_065_),
    .ZN(_066_)
  );
  INV_X1 _188_ (
    .A(_064_),
    .ZN(_067_)
  );
  XNOR2_X1 _189_ (
    .A(_067_),
    .B(_063_),
    .ZN(_068_)
  );
  INV_X1 _190_ (
    .A(_062_),
    .ZN(_069_)
  );
  OAI21_X2 _191_ (
    .A(_068_),
    .B1(_069_),
    .B2(_060_),
    .ZN(_070_)
  );
  NAND2_X1 _192_ (
    .A1(_066_),
    .A2(_070_),
    .ZN(_071_)
  );
  AOI21_X1 _193_ (
    .A(_049_),
    .B1(_050_),
    .B2(_051_),
    .ZN(_072_)
  );
  XOR2_X1 _194_ (
    .A(_071_),
    .B(_072_),
    .Z(_002_)
  );
  NAND4_X1 _195_ (
    .A1(_066_),
    .A2(_070_),
    .A3(_051_),
    .A4(_050_),
    .ZN(_073_)
  );
  NAND3_X1 _196_ (
    .A1(_066_),
    .A2(_070_),
    .A3(_049_),
    .ZN(_074_)
  );
  NAND3_X1 _197_ (
    .A1(_073_),
    .A2(_070_),
    .A3(_074_),
    .ZN(_075_)
  );
  NOR2_X1 _198_ (
    .A1(_055_),
    .A2(_058_),
    .ZN(_076_)
  );
  NAND2_X1 _199_ (
    .A1(_057_),
    .A2(_059_),
    .ZN(_077_)
  );
  AOI21_X2 _200_ (
    .A(_076_),
    .B1(_077_),
    .B2(_054_),
    .ZN(_078_)
  );
  INV_X1 _201_ (
    .A(_078_),
    .ZN(_079_)
  );
  NAND2_X2 _202_ (
    .A1(_042_),
    .A2(_046_),
    .ZN(_080_)
  );
  NAND3_X2 _203_ (
    .A1(_080_),
    .A2(_056_),
    .A3(_039_),
    .ZN(_081_)
  );
  NAND2_X4 _204_ (
    .A1(_056_),
    .A2(_039_),
    .ZN(_082_)
  );
  NAND3_X2 _205_ (
    .A1(_082_),
    .A2(_042_),
    .A3(_046_),
    .ZN(_083_)
  );
  NAND2_X4 _206_ (
    .A1(_037_),
    .A2(_115_),
    .ZN(_084_)
  );
  INV_X1 _207_ (
    .A(_084_),
    .ZN(_085_)
  );
  NAND3_X2 _208_ (
    .A1(_081_),
    .A2(_083_),
    .A3(_085_),
    .ZN(_086_)
  );
  INV_X4 _209_ (
    .A(_086_),
    .ZN(_087_)
  );
  AOI21_X4 _210_ (
    .A(_085_),
    .B1(_081_),
    .B2(_083_),
    .ZN(_088_)
  );
  NOR2_X4 _211_ (
    .A1(_063_),
    .A2(_064_),
    .ZN(_089_)
  );
  INV_X1 _212_ (
    .A(_089_),
    .ZN(_090_)
  );
  NOR3_X4 _213_ (
    .A1(_087_),
    .A2(_088_),
    .A3(_090_),
    .ZN(_091_)
  );
  NAND2_X1 _214_ (
    .A1(_081_),
    .A2(_083_),
    .ZN(_092_)
  );
  NAND2_X1 _215_ (
    .A1(_092_),
    .A2(_084_),
    .ZN(_093_)
  );
  AOI21_X1 _216_ (
    .A(_089_),
    .B1(_093_),
    .B2(_086_),
    .ZN(_094_)
  );
  OAI21_X4 _217_ (
    .A(_079_),
    .B1(_091_),
    .B2(_094_),
    .ZN(_095_)
  );
  OAI21_X2 _218_ (
    .A(_090_),
    .B1(_087_),
    .B2(_088_),
    .ZN(_096_)
  );
  NAND3_X1 _219_ (
    .A1(_093_),
    .A2(_086_),
    .A3(_089_),
    .ZN(_097_)
  );
  NAND3_X2 _220_ (
    .A1(_096_),
    .A2(_097_),
    .A3(_078_),
    .ZN(_098_)
  );
  NAND2_X1 _221_ (
    .A1(_095_),
    .A2(_098_),
    .ZN(_099_)
  );
  XNOR2_X1 _222_ (
    .A(_075_),
    .B(_099_),
    .ZN(_003_)
  );
  AOI21_X1 _223_ (
    .A(_078_),
    .B1(_096_),
    .B2(_097_),
    .ZN(_100_)
  );
  AOI21_X1 _224_ (
    .A(_100_),
    .B1(_075_),
    .B2(_098_),
    .ZN(_101_)
  );
  OAI21_X4 _225_ (
    .A(_089_),
    .B1(_087_),
    .B2(_088_),
    .ZN(_102_)
  );
  NOR2_X2 _226_ (
    .A1(_080_),
    .A2(_082_),
    .ZN(_103_)
  );
  INV_X1 _227_ (
    .A(_103_),
    .ZN(_104_)
  );
  NAND2_X1 _228_ (
    .A1(_042_),
    .A2(_115_),
    .ZN(_105_)
  );
  NAND3_X1 _229_ (
    .A1(_105_),
    .A2(_056_),
    .A3(_046_),
    .ZN(_106_)
  );
  NAND2_X1 _230_ (
    .A1(_056_),
    .A2(_046_),
    .ZN(_107_)
  );
  NAND3_X1 _231_ (
    .A1(_107_),
    .A2(_042_),
    .A3(_115_),
    .ZN(_108_)
  );
  NAND2_X1 _232_ (
    .A1(_106_),
    .A2(_108_),
    .ZN(_109_)
  );
  XNOR2_X1 _233_ (
    .A(_080_),
    .B(_082_),
    .ZN(_110_)
  );
  OAI211_X2 _234_ (
    .A(_104_),
    .B(_109_),
    .C1(_110_),
    .C2(_084_),
    .ZN(_111_)
  );
  AND2_X1 _235_ (
    .A1(_106_),
    .A2(_108_),
    .ZN(_008_)
  );
  AOI21_X2 _236_ (
    .A(_084_),
    .B1(_081_),
    .B2(_083_),
    .ZN(_009_)
  );
  OAI21_X2 _237_ (
    .A(_008_),
    .B1(_009_),
    .B2(_103_),
    .ZN(_010_)
  );
  AND3_X1 _238_ (
    .A1(_102_),
    .A2(_111_),
    .A3(_010_),
    .ZN(_011_)
  );
  AOI21_X1 _239_ (
    .A(_102_),
    .B1(_111_),
    .B2(_010_),
    .ZN(_012_)
  );
  NOR2_X1 _240_ (
    .A1(_011_),
    .A2(_012_),
    .ZN(_013_)
  );
  XNOR2_X1 _241_ (
    .A(_101_),
    .B(_013_),
    .ZN(_004_)
  );
  NAND3_X2 _242_ (
    .A1(_102_),
    .A2(_111_),
    .A3(_010_),
    .ZN(_014_)
  );
  AOI21_X2 _243_ (
    .A(_012_),
    .B1(_100_),
    .B2(_014_),
    .ZN(_015_)
  );
  INV_X1 _244_ (
    .A(_075_),
    .ZN(_016_)
  );
  NAND2_X1 _245_ (
    .A1(_111_),
    .A2(_010_),
    .ZN(_017_)
  );
  AOI21_X1 _246_ (
    .A(_090_),
    .B1(_093_),
    .B2(_086_),
    .ZN(_018_)
  );
  NAND2_X2 _247_ (
    .A1(_017_),
    .A2(_018_),
    .ZN(_019_)
  );
  NAND4_X2 _248_ (
    .A1(_095_),
    .A2(_019_),
    .A3(_098_),
    .A4(_014_),
    .ZN(_020_)
  );
  OAI21_X4 _249_ (
    .A(_015_),
    .B1(_016_),
    .B2(_020_),
    .ZN(_021_)
  );
  OAI21_X1 _250_ (
    .A(_109_),
    .B1(_009_),
    .B2(_103_),
    .ZN(_022_)
  );
  OAI21_X1 _251_ (
    .A(_022_),
    .B1(_105_),
    .B2(_107_),
    .ZN(_023_)
  );
  AND2_X1 _252_ (
    .A1(_056_),
    .A2(_115_),
    .ZN(_024_)
  );
  XNOR2_X1 _253_ (
    .A(_023_),
    .B(_024_),
    .ZN(_025_)
  );
  XNOR2_X2 _254_ (
    .A(_021_),
    .B(_025_),
    .ZN(_005_)
  );
  NAND2_X1 _255_ (
    .A1(_023_),
    .A2(_024_),
    .ZN(_026_)
  );
  INV_X1 _256_ (
    .A(_026_),
    .ZN(_027_)
  );
  OAI21_X1 _257_ (
    .A(_019_),
    .B1(_011_),
    .B2(_095_),
    .ZN(_028_)
  );
  AND4_X4 _258_ (
    .A1(_095_),
    .A2(_019_),
    .A3(_098_),
    .A4(_014_),
    .ZN(_029_)
  );
  AOI21_X1 _259_ (
    .A(_028_),
    .B1(_029_),
    .B2(_075_),
    .ZN(_030_)
  );
  OAI21_X2 _260_ (
    .A(_027_),
    .B1(_030_),
    .B2(_025_),
    .ZN(_031_)
  );
  INV_X1 _261_ (
    .A(_025_),
    .ZN(_032_)
  );
  NAND3_X1 _262_ (
    .A1(_021_),
    .A2(_032_),
    .A3(_026_),
    .ZN(_033_)
  );
  NAND2_X2 _263_ (
    .A1(_031_),
    .A2(_033_),
    .ZN(_006_)
  );
  assign a = { \ha3.c , \ha3.s , \ha2.c , \fa0.cy , \fa0.h2.s , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.a  = { \ha3.c , \ha3.s , \ha2.c , \fa0.cy , \fa0.h2.s , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.b  = { 2'h0, \fa2.h2.s , \ha2.s , \ha1.s , \ha0.s , ip_1_0, 1'h0 };
  assign \add.s [0] = ip_0_0;
  assign b = { \fa2.h2.s , \ha2.s , \ha1.s , \ha0.s , ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.sm  = \fa0.h2.s ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa1.h2.b ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa2.h1.b ;
  assign \fa2.c  = \fa1.cy ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.h2.b  = \fa1.cy ;
  assign \fa2.sm  = \fa2.h2.s ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \ha1.b  = \ha0.c ;
  assign \ha2.a  = \ha1.c ;
  assign \ha2.b  = \fa1.h2.s ;
  assign \ha3.b  = \fa2.cy ;
  assign ip_0_2 = \ha0.a ;
  assign ip_0_3 = \fa0.h1.a ;
  assign ip_1_1 = \ha0.b ;
  assign ip_1_2 = \fa0.h1.b ;
  assign ip_1_3 = \fa1.h1.a ;
  assign ip_2_1 = \fa0.h2.b ;
  assign ip_2_2 = \fa1.h1.b ;
  assign ip_2_3 = \fa2.h1.a ;
  assign ip_3_0 = \ha1.a ;
  assign ip_3_1 = \fa1.h2.b ;
  assign ip_3_2 = \fa2.h1.b ;
  assign ip_3_3 = \ha3.a ;
  assign o = { \add.s [7:1], ip_0_0 };
  assign p0 = \ha0.c ;
  assign p1 = \ha0.s ;
  assign p10 = \fa2.cy ;
  assign p11 = \fa2.h2.s ;
  assign p12 = \ha3.c ;
  assign p13 = \ha3.s ;
  assign p2 = \fa0.cy ;
  assign p3 = \fa0.h2.s ;
  assign p4 = \ha1.c ;
  assign p5 = \ha1.s ;
  assign p6 = \fa1.cy ;
  assign p7 = \fa1.h2.s ;
  assign p8 = \ha2.c ;
  assign p9 = \ha2.s ;
  assign s = { \add.s [7:1], ip_0_0 };
  assign _116_ = y[0];
  assign _112_ = x[0];
  assign ip_0_0 = _007_;
  assign _117_ = y[1];
  assign _118_ = y[2];
  assign _119_ = y[3];
  assign _113_ = x[1];
  assign _114_ = x[2];
  assign _115_ = x[3];
  assign \add.s [1] = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
