/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:3.1-63.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.82-91.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.13-4.14" *)
  wire _127_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.13-4.14" *)
  wire _128_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.13-4.14" *)
  wire _129_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.13-4.14" *)
  wire _130_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.15-4.16" *)
  wire _131_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.15-4.16" *)
  wire _132_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.15-4.16" *)
  wire _133_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.15-4.16" *)
  wire _134_;
  wire _135_;
  wire _136_;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:35.12-35.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:89.13-89.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:89.15-89.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:146.8-146.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.7-145.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.17-145.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:146.13-146.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.12-145.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.22-145.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:146.8-146.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.7-145.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.17-145.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:146.13-146.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.12-145.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:145.22-145.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.46-91.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.144-91.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.54-91.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.162-91.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.126-91.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.90-91.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.123-91.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.49-91.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.67-91.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.77-91.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:110.8-110.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.62-91.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.16-91.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.11-91.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.36-91.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:112.8-112.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.72-91.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.93-91.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.118-91.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.21-91.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:114.8-114.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.147-91.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:140.8-140.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.7-139.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.17-139.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:139.12-139.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.82-91.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.26-91.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.41-91.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.98-91.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.103-91.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.31-91.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.6-91.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:91.108-91.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:90.14-90.15" *)
  wire [7:0] \add.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:35.14-35.15" *)
  wire [7:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.7-72.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.9-72.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.11-72.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.8-73.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.11-73.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.6-74.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.8-74.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.10-74.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.7-72.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.9-72.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.11-72.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.8-73.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.11-73.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.6-74.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.8-74.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.10-74.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.7-72.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.9-72.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.11-72.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.8-73.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.11-73.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.6-74.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.8-74.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.10-74.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.7-72.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.9-72.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.11-72.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.8-73.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.11-73.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.6-74.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.8-74.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.10-74.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.7-72.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.9-72.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:72.11-72.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.8-73.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:73.11-73.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.6-74.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.8-74.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:74.10-74.11" *)
  wire \fa4.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha3.s ;
  (* hdlname = "ha4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha4.a ;
  (* hdlname = "ha4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha4.b ;
  (* hdlname = "ha4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha4.c ;
  (* hdlname = "ha4 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha4.s ;
  (* hdlname = "ha5 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.7-66.8" *)
  wire \ha5.a ;
  (* hdlname = "ha5 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:66.9-66.10" *)
  wire \ha5.b ;
  (* hdlname = "ha5 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.8-67.9" *)
  wire \ha5.c ;
  (* hdlname = "ha5 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:67.10-67.11" *)
  wire \ha5.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.68-7.71" *)
  wire p18;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.72-7.75" *)
  wire p19;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.76-7.79" *)
  wire p20;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.80-7.83" *)
  wire p21;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:36.12-36.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_4b8be675664ff9bc84803f5486ba4940.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  AND2_X1 _137_ (
    .A1(_131_),
    .A2(_127_),
    .ZN(_007_)
  );
  BUF_X4 _138_ (
    .A(_128_),
    .Z(_049_)
  );
  NAND2_X1 _139_ (
    .A1(_131_),
    .A2(_049_),
    .ZN(_050_)
  );
  NAND2_X1 _140_ (
    .A1(_127_),
    .A2(_132_),
    .ZN(_051_)
  );
  XOR2_X1 _141_ (
    .A(_050_),
    .B(_051_),
    .Z(_000_)
  );
  NAND2_X1 _142_ (
    .A1(_132_),
    .A2(_049_),
    .ZN(_052_)
  );
  BUF_X4 _143_ (
    .A(_133_),
    .Z(_053_)
  );
  NAND2_X2 _144_ (
    .A1(_127_),
    .A2(_053_),
    .ZN(_054_)
  );
  XNOR2_X2 _145_ (
    .A(_052_),
    .B(_054_),
    .ZN(_055_)
  );
  BUF_X4 _146_ (
    .A(_129_),
    .Z(_056_)
  );
  NAND2_X1 _147_ (
    .A1(_131_),
    .A2(_056_),
    .ZN(_057_)
  );
  XOR2_X2 _148_ (
    .A(_055_),
    .B(_057_),
    .Z(_058_)
  );
  NOR2_X1 _149_ (
    .A1(_050_),
    .A2(_051_),
    .ZN(_059_)
  );
  XOR2_X1 _150_ (
    .A(_058_),
    .B(_059_),
    .Z(_001_)
  );
  BUF_X2 _151_ (
    .A(_130_),
    .Z(_060_)
  );
  NAND2_X1 _152_ (
    .A1(_131_),
    .A2(_060_),
    .ZN(_061_)
  );
  NAND2_X2 _153_ (
    .A1(_053_),
    .A2(_049_),
    .ZN(_062_)
  );
  BUF_X4 _154_ (
    .A(_134_),
    .Z(_063_)
  );
  NAND3_X4 _155_ (
    .A1(_062_),
    .A2(_127_),
    .A3(_063_),
    .ZN(_064_)
  );
  NAND2_X4 _156_ (
    .A1(_127_),
    .A2(_063_),
    .ZN(_065_)
  );
  NAND3_X4 _157_ (
    .A1(_065_),
    .A2(_053_),
    .A3(_049_),
    .ZN(_066_)
  );
  NAND2_X2 _158_ (
    .A1(_132_),
    .A2(_056_),
    .ZN(_067_)
  );
  INV_X4 _159_ (
    .A(_067_),
    .ZN(_068_)
  );
  AND3_X4 _160_ (
    .A1(_064_),
    .A2(_066_),
    .A3(_068_),
    .ZN(_069_)
  );
  AOI21_X4 _161_ (
    .A(_068_),
    .B1(_064_),
    .B2(_066_),
    .ZN(_070_)
  );
  OAI21_X4 _162_ (
    .A(_061_),
    .B1(_069_),
    .B2(_070_),
    .ZN(_071_)
  );
  NAND2_X4 _163_ (
    .A1(_064_),
    .A2(_066_),
    .ZN(_072_)
  );
  NAND2_X4 _164_ (
    .A1(_072_),
    .A2(_067_),
    .ZN(_073_)
  );
  NAND3_X2 _165_ (
    .A1(_064_),
    .A2(_066_),
    .A3(_068_),
    .ZN(_074_)
  );
  INV_X1 _166_ (
    .A(_061_),
    .ZN(_075_)
  );
  NAND3_X2 _167_ (
    .A1(_073_),
    .A2(_074_),
    .A3(_075_),
    .ZN(_076_)
  );
  OR2_X1 _168_ (
    .A1(_052_),
    .A2(_054_),
    .ZN(_077_)
  );
  OAI21_X2 _169_ (
    .A(_077_),
    .B1(_055_),
    .B2(_057_),
    .ZN(_078_)
  );
  AND3_X2 _170_ (
    .A1(_071_),
    .A2(_076_),
    .A3(_078_),
    .ZN(_079_)
  );
  AOI21_X2 _171_ (
    .A(_078_),
    .B1(_071_),
    .B2(_076_),
    .ZN(_080_)
  );
  NOR2_X1 _172_ (
    .A1(_079_),
    .A2(_080_),
    .ZN(_081_)
  );
  NAND2_X1 _173_ (
    .A1(_058_),
    .A2(_059_),
    .ZN(_082_)
  );
  XOR2_X1 _174_ (
    .A(_081_),
    .B(_082_),
    .Z(_002_)
  );
  OAI211_X2 _175_ (
    .A(_058_),
    .B(_059_),
    .C1(_079_),
    .C2(_080_),
    .ZN(_083_)
  );
  NAND2_X1 _176_ (
    .A1(_071_),
    .A2(_076_),
    .ZN(_084_)
  );
  NAND2_X1 _177_ (
    .A1(_084_),
    .A2(_078_),
    .ZN(_085_)
  );
  NAND2_X2 _178_ (
    .A1(_083_),
    .A2(_085_),
    .ZN(_086_)
  );
  NAND2_X4 _179_ (
    .A1(_072_),
    .A2(_068_),
    .ZN(_087_)
  );
  NOR2_X2 _180_ (
    .A1(_062_),
    .A2(_065_),
    .ZN(_088_)
  );
  INV_X2 _181_ (
    .A(_088_),
    .ZN(_089_)
  );
  NAND2_X4 _182_ (
    .A1(_053_),
    .A2(_056_),
    .ZN(_090_)
  );
  NAND3_X2 _183_ (
    .A1(_090_),
    .A2(_063_),
    .A3(_049_),
    .ZN(_091_)
  );
  NAND2_X4 _184_ (
    .A1(_063_),
    .A2(_049_),
    .ZN(_092_)
  );
  NAND3_X4 _185_ (
    .A1(_092_),
    .A2(_053_),
    .A3(_056_),
    .ZN(_093_)
  );
  NAND2_X2 _186_ (
    .A1(_132_),
    .A2(_060_),
    .ZN(_094_)
  );
  INV_X1 _187_ (
    .A(_094_),
    .ZN(_095_)
  );
  AND3_X2 _188_ (
    .A1(_091_),
    .A2(_093_),
    .A3(_095_),
    .ZN(_096_)
  );
  AOI21_X2 _189_ (
    .A(_095_),
    .B1(_091_),
    .B2(_093_),
    .ZN(_097_)
  );
  OAI211_X4 _190_ (
    .A(_087_),
    .B(_089_),
    .C1(_096_),
    .C2(_097_),
    .ZN(_098_)
  );
  NAND2_X2 _191_ (
    .A1(_091_),
    .A2(_093_),
    .ZN(_099_)
  );
  NAND2_X2 _192_ (
    .A1(_099_),
    .A2(_094_),
    .ZN(_100_)
  );
  NAND3_X2 _193_ (
    .A1(_091_),
    .A2(_093_),
    .A3(_095_),
    .ZN(_101_)
  );
  AOI21_X2 _194_ (
    .A(_067_),
    .B1(_064_),
    .B2(_066_),
    .ZN(_102_)
  );
  OAI211_X4 _195_ (
    .A(_100_),
    .B(_101_),
    .C1(_102_),
    .C2(_088_),
    .ZN(_103_)
  );
  AOI21_X4 _196_ (
    .A(_061_),
    .B1(_073_),
    .B2(_074_),
    .ZN(_104_)
  );
  AND3_X2 _197_ (
    .A1(_098_),
    .A2(_103_),
    .A3(_104_),
    .ZN(_105_)
  );
  AOI21_X2 _198_ (
    .A(_104_),
    .B1(_098_),
    .B2(_103_),
    .ZN(_106_)
  );
  NOR2_X2 _199_ (
    .A1(_105_),
    .A2(_106_),
    .ZN(_107_)
  );
  XNOR2_X1 _200_ (
    .A(_086_),
    .B(_107_),
    .ZN(_003_)
  );
  INV_X1 _201_ (
    .A(_107_),
    .ZN(_108_)
  );
  NAND2_X1 _202_ (
    .A1(_086_),
    .A2(_108_),
    .ZN(_109_)
  );
  NAND2_X2 _203_ (
    .A1(_098_),
    .A2(_103_),
    .ZN(_110_)
  );
  NAND2_X1 _204_ (
    .A1(_110_),
    .A2(_104_),
    .ZN(_111_)
  );
  AOI22_X4 _205_ (
    .A1(_087_),
    .A2(_089_),
    .B1(_100_),
    .B2(_101_),
    .ZN(_112_)
  );
  INV_X1 _206_ (
    .A(_112_),
    .ZN(_113_)
  );
  NAND2_X1 _207_ (
    .A1(_053_),
    .A2(_060_),
    .ZN(_114_)
  );
  NAND3_X1 _208_ (
    .A1(_114_),
    .A2(_063_),
    .A3(_056_),
    .ZN(_115_)
  );
  NAND2_X1 _209_ (
    .A1(_063_),
    .A2(_056_),
    .ZN(_116_)
  );
  NAND3_X1 _210_ (
    .A1(_116_),
    .A2(_053_),
    .A3(_060_),
    .ZN(_117_)
  );
  NAND2_X1 _211_ (
    .A1(_115_),
    .A2(_117_),
    .ZN(_118_)
  );
  NOR2_X2 _212_ (
    .A1(_090_),
    .A2(_092_),
    .ZN(_119_)
  );
  INV_X1 _213_ (
    .A(_119_),
    .ZN(_120_)
  );
  NAND2_X1 _214_ (
    .A1(_118_),
    .A2(_120_),
    .ZN(_121_)
  );
  NAND3_X1 _215_ (
    .A1(_119_),
    .A2(_115_),
    .A3(_117_),
    .ZN(_122_)
  );
  NAND2_X1 _216_ (
    .A1(_121_),
    .A2(_122_),
    .ZN(_123_)
  );
  AOI21_X2 _217_ (
    .A(_094_),
    .B1(_091_),
    .B2(_093_),
    .ZN(_124_)
  );
  INV_X1 _218_ (
    .A(_124_),
    .ZN(_125_)
  );
  NAND2_X1 _219_ (
    .A1(_123_),
    .A2(_125_),
    .ZN(_126_)
  );
  NAND3_X1 _220_ (
    .A1(_121_),
    .A2(_124_),
    .A3(_122_),
    .ZN(_008_)
  );
  NAND2_X1 _221_ (
    .A1(_126_),
    .A2(_008_),
    .ZN(_009_)
  );
  NAND3_X1 _222_ (
    .A1(_111_),
    .A2(_113_),
    .A3(_009_),
    .ZN(_010_)
  );
  AND2_X1 _223_ (
    .A1(_126_),
    .A2(_008_),
    .ZN(_011_)
  );
  OAI21_X2 _224_ (
    .A(_075_),
    .B1(_069_),
    .B2(_070_),
    .ZN(_012_)
  );
  AOI21_X4 _225_ (
    .A(_012_),
    .B1(_098_),
    .B2(_103_),
    .ZN(_013_)
  );
  OAI21_X2 _226_ (
    .A(_011_),
    .B1(_013_),
    .B2(_112_),
    .ZN(_014_)
  );
  NAND2_X2 _227_ (
    .A1(_010_),
    .A2(_014_),
    .ZN(_015_)
  );
  XNOR2_X2 _228_ (
    .A(_109_),
    .B(_015_),
    .ZN(_004_)
  );
  NAND2_X1 _229_ (
    .A1(_123_),
    .A2(_124_),
    .ZN(_016_)
  );
  AOI21_X1 _230_ (
    .A(_112_),
    .B1(_110_),
    .B2(_104_),
    .ZN(_017_)
  );
  OAI21_X1 _231_ (
    .A(_016_),
    .B1(_017_),
    .B2(_011_),
    .ZN(_018_)
  );
  NAND2_X1 _232_ (
    .A1(_118_),
    .A2(_119_),
    .ZN(_019_)
  );
  INV_X1 _233_ (
    .A(_053_),
    .ZN(_020_)
  );
  INV_X1 _234_ (
    .A(_056_),
    .ZN(_021_)
  );
  OAI211_X1 _235_ (
    .A(_063_),
    .B(_060_),
    .C1(_020_),
    .C2(_021_),
    .ZN(_022_)
  );
  XNOR2_X1 _236_ (
    .A(_019_),
    .B(_022_),
    .ZN(_023_)
  );
  NAND2_X1 _237_ (
    .A1(_018_),
    .A2(_023_),
    .ZN(_024_)
  );
  OAI21_X2 _238_ (
    .A(_009_),
    .B1(_013_),
    .B2(_112_),
    .ZN(_025_)
  );
  INV_X1 _239_ (
    .A(_023_),
    .ZN(_026_)
  );
  NAND3_X1 _240_ (
    .A1(_025_),
    .A2(_016_),
    .A3(_026_),
    .ZN(_027_)
  );
  NAND2_X2 _241_ (
    .A1(_024_),
    .A2(_027_),
    .ZN(_028_)
  );
  AOI21_X2 _242_ (
    .A(_107_),
    .B1(_010_),
    .B2(_014_),
    .ZN(_029_)
  );
  NAND2_X1 _243_ (
    .A1(_029_),
    .A2(_086_),
    .ZN(_030_)
  );
  XNOR2_X2 _244_ (
    .A(_028_),
    .B(_030_),
    .ZN(_005_)
  );
  AND3_X1 _245_ (
    .A1(_025_),
    .A2(_016_),
    .A3(_026_),
    .ZN(_031_)
  );
  AOI21_X1 _246_ (
    .A(_026_),
    .B1(_025_),
    .B2(_016_),
    .ZN(_032_)
  );
  OAI211_X1 _247_ (
    .A(_086_),
    .B(_029_),
    .C1(_031_),
    .C2(_032_),
    .ZN(_033_)
  );
  NOR2_X1 _248_ (
    .A1(_114_),
    .A2(_116_),
    .ZN(_034_)
  );
  AND2_X1 _249_ (
    .A1(_063_),
    .A2(_060_),
    .ZN(_035_)
  );
  NAND2_X1 _250_ (
    .A1(_034_),
    .A2(_035_),
    .ZN(_036_)
  );
  INV_X1 _251_ (
    .A(_036_),
    .ZN(_037_)
  );
  NAND2_X1 _252_ (
    .A1(_018_),
    .A2(_026_),
    .ZN(_038_)
  );
  NOR2_X1 _253_ (
    .A1(_019_),
    .A2(_022_),
    .ZN(_039_)
  );
  INV_X1 _254_ (
    .A(_039_),
    .ZN(_040_)
  );
  AOI21_X1 _255_ (
    .A(_037_),
    .B1(_038_),
    .B2(_040_),
    .ZN(_041_)
  );
  AOI21_X2 _256_ (
    .A(_023_),
    .B1(_025_),
    .B2(_016_),
    .ZN(_042_)
  );
  NOR3_X1 _257_ (
    .A1(_042_),
    .A2(_039_),
    .A3(_036_),
    .ZN(_043_)
  );
  OAI21_X1 _258_ (
    .A(_033_),
    .B1(_041_),
    .B2(_043_),
    .ZN(_044_)
  );
  NAND3_X1 _259_ (
    .A1(_038_),
    .A2(_040_),
    .A3(_037_),
    .ZN(_045_)
  );
  AND3_X4 _260_ (
    .A1(_015_),
    .A2(_086_),
    .A3(_108_),
    .ZN(_046_)
  );
  OAI21_X2 _261_ (
    .A(_036_),
    .B1(_042_),
    .B2(_039_),
    .ZN(_047_)
  );
  NAND4_X4 _262_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_047_),
    .A4(_028_),
    .ZN(_048_)
  );
  NAND2_X2 _263_ (
    .A1(_044_),
    .A2(_048_),
    .ZN(_006_)
  );
  assign a = { \ha5.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \fa0.cy , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.a  = { \ha5.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \fa0.cy , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.b  = { \fa4.cy , 3'h0, \ha0.s , 1'h0, ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = \add.g3_3 ;
  assign \add.black3_2.gik  = \add.g3_3 ;
  assign \add.black3_2.gkj  = 1'h0;
  assign \add.black5_4.gij  = 1'h0;
  assign \add.black5_4.gik  = 1'h0;
  assign \add.black5_4.gkj  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = 1'h0;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = \add.g3_3 ;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = 1'h0;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = 1'h0;
  assign \add.g5_5  = 1'h0;
  assign \add.g6_0  = \add.c6 ;
  assign \add.g6_6  = 1'h0;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = 1'h0;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gik  = \add.g3_3 ;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = 1'h0;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gik  = 1'h0;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = 1'h0;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \fa4.cy , 3'h0, \ha0.s , 1'h0, ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pkj ;
  assign \fa0.sm  = \add.black3_2.pkj ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa1.h2.b ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa1.cy ;
  assign \fa2.c  = \fa2.h2.b ;
  assign \fa2.h1.b  = \fa1.cy ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.h2.s  = \add.black5_4.pkj ;
  assign \fa2.sm  = \add.black5_4.pkj ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa3.h1.b ;
  assign \fa3.c  = \fa2.cy ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.h2.b  = \fa2.cy ;
  assign \fa3.h2.s  = \add.black5_4.pik ;
  assign \fa3.sm  = \add.black5_4.pik ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa4.h1.b ;
  assign \fa4.c  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.h2.b  = \fa3.cy ;
  assign \fa4.h2.s  = \add.grey6.pik ;
  assign \fa4.sm  = \add.grey6.pik ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \ha0.b  = \fa1.h2.s ;
  assign \ha0.c  = \fa2.h2.b ;
  assign \ha2.b  = \ha1.s ;
  assign \ha2.c  = \fa3.h1.b ;
  assign \ha2.s  = \fa2.h1.a ;
  assign \ha4.a  = \ha3.s ;
  assign \ha4.b  = \ha1.c ;
  assign \ha4.c  = \fa4.h1.a ;
  assign \ha4.s  = \fa3.h1.a ;
  assign \ha5.b  = \ha3.c ;
  assign \ha5.s  = \fa4.h1.b ;
  assign ip_0_2 = \fa0.h1.a ;
  assign ip_0_3 = \fa1.h1.a ;
  assign ip_1_1 = \fa0.h1.b ;
  assign ip_1_2 = \fa1.h1.b ;
  assign ip_1_3 = \ha1.a ;
  assign ip_2_0 = \fa0.h2.b ;
  assign ip_2_1 = \fa1.h2.b ;
  assign ip_2_2 = \ha1.b ;
  assign ip_2_3 = \ha3.a ;
  assign ip_3_0 = \ha0.a ;
  assign ip_3_1 = \ha2.a ;
  assign ip_3_2 = \ha3.b ;
  assign ip_3_3 = \ha5.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.cy ;
  assign p1 = \add.black3_2.pkj ;
  assign p10 = \fa2.cy ;
  assign p11 = \add.black5_4.pkj ;
  assign p12 = \ha3.c ;
  assign p13 = \ha3.s ;
  assign p14 = \fa4.h1.a ;
  assign p15 = \fa3.h1.a ;
  assign p16 = \fa3.cy ;
  assign p17 = \add.black5_4.pik ;
  assign p18 = \ha5.c ;
  assign p19 = \fa4.h1.b ;
  assign p2 = \fa1.cy ;
  assign p20 = \fa4.cy ;
  assign p21 = \add.grey6.pik ;
  assign p3 = \fa1.h2.s ;
  assign p4 = \fa2.h2.b ;
  assign p5 = \ha0.s ;
  assign p6 = \ha1.c ;
  assign p7 = \ha1.s ;
  assign p8 = \fa3.h1.b ;
  assign p9 = \fa2.h1.a ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _131_ = y[0];
  assign _127_ = x[0];
  assign ip_0_0 = _007_;
  assign _132_ = y[1];
  assign _133_ = y[2];
  assign _134_ = y[3];
  assign _128_ = x[1];
  assign _129_ = x[2];
  assign _130_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
