/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:3.1-61.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.82-89.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.13-4.14" *)
  wire _132_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.13-4.14" *)
  wire _133_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.13-4.14" *)
  wire _134_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.13-4.14" *)
  wire _135_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.15-4.16" *)
  wire _136_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.15-4.16" *)
  wire _137_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.15-4.16" *)
  wire _138_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.15-4.16" *)
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:33.12-33.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:87.13-87.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:87.15-87.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:144.8-144.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.7-143.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.17-143.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:144.13-144.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.12-143.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.22-143.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:144.8-144.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.7-143.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.17-143.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:144.13-144.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.12-143.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:143.22-143.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.46-89.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.144-89.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.54-89.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.162-89.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.126-89.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.90-89.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.123-89.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.49-89.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.67-89.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.77-89.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:108.8-108.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.62-89.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.16-89.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.11-89.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.36-89.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:110.8-110.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.72-89.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.93-89.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.118-89.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.21-89.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:112.8-112.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.147-89.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:138.8-138.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.7-137.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.17-137.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:137.12-137.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.82-89.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.26-89.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.41-89.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.98-89.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.103-89.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.31-89.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.6-89.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:89.108-89.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:88.14-88.15" *)
  wire [7:0] \add.s ;
  wire [5:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.7-70.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.9-70.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.11-70.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.8-71.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.11-71.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.6-72.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.8-72.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.10-72.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.7-70.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.9-70.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.11-70.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.8-71.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.11-71.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.6-72.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.8-72.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.10-72.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.7-70.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.9-70.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.11-70.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.8-71.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.11-71.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.6-72.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.8-72.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.10-72.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.7-70.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.9-70.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.11-70.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.8-71.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.11-71.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.6-72.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.8-72.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.10-72.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.7-70.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.9-70.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:70.11-70.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.8-71.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:71.11-71.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.6-72.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.8-72.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:72.10-72.11" *)
  wire \fa4.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.7-64.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:64.9-64.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.8-65.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:65.10-65.11" *)
  wire \ha3.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:34.12-34.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_42c3e3d2b5d8c33aea24875e50b6c2b5.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  BUF_X4 _143_ (
    .A(_132_),
    .Z(_054_)
  );
  AND2_X1 _144_ (
    .A1(_136_),
    .A2(_054_),
    .ZN(_007_)
  );
  BUF_X4 _145_ (
    .A(_133_),
    .Z(_055_)
  );
  NAND2_X1 _146_ (
    .A1(_136_),
    .A2(_055_),
    .ZN(_056_)
  );
  NAND2_X1 _147_ (
    .A1(_054_),
    .A2(_137_),
    .ZN(_057_)
  );
  XOR2_X1 _148_ (
    .A(_056_),
    .B(_057_),
    .Z(_000_)
  );
  NAND2_X1 _149_ (
    .A1(_137_),
    .A2(_055_),
    .ZN(_058_)
  );
  BUF_X4 _150_ (
    .A(_138_),
    .Z(_059_)
  );
  NAND3_X1 _151_ (
    .A1(_058_),
    .A2(_054_),
    .A3(_059_),
    .ZN(_060_)
  );
  NAND2_X1 _152_ (
    .A1(_054_),
    .A2(_059_),
    .ZN(_061_)
  );
  NAND3_X1 _153_ (
    .A1(_061_),
    .A2(_137_),
    .A3(_055_),
    .ZN(_062_)
  );
  NAND2_X1 _154_ (
    .A1(_060_),
    .A2(_062_),
    .ZN(_063_)
  );
  BUF_X4 _155_ (
    .A(_134_),
    .Z(_064_)
  );
  NAND2_X1 _156_ (
    .A1(_136_),
    .A2(_064_),
    .ZN(_065_)
  );
  INV_X1 _157_ (
    .A(_065_),
    .ZN(_066_)
  );
  XNOR2_X1 _158_ (
    .A(_063_),
    .B(_066_),
    .ZN(_067_)
  );
  NOR2_X1 _159_ (
    .A1(_056_),
    .A2(_057_),
    .ZN(_068_)
  );
  XNOR2_X1 _160_ (
    .A(_067_),
    .B(_068_),
    .ZN(_001_)
  );
  NOR2_X1 _161_ (
    .A1(_058_),
    .A2(_061_),
    .ZN(_069_)
  );
  AOI21_X1 _162_ (
    .A(_069_),
    .B1(_063_),
    .B2(_066_),
    .ZN(_070_)
  );
  NAND2_X2 _163_ (
    .A1(_059_),
    .A2(_055_),
    .ZN(_071_)
  );
  BUF_X8 _164_ (
    .A(_139_),
    .Z(_072_)
  );
  NAND3_X4 _165_ (
    .A1(_071_),
    .A2(_054_),
    .A3(_072_),
    .ZN(_073_)
  );
  NAND2_X4 _166_ (
    .A1(_054_),
    .A2(_072_),
    .ZN(_074_)
  );
  NAND3_X4 _167_ (
    .A1(_074_),
    .A2(_059_),
    .A3(_055_),
    .ZN(_075_)
  );
  NAND2_X2 _168_ (
    .A1(_137_),
    .A2(_064_),
    .ZN(_076_)
  );
  INV_X2 _169_ (
    .A(_076_),
    .ZN(_077_)
  );
  AND3_X2 _170_ (
    .A1(_073_),
    .A2(_075_),
    .A3(_077_),
    .ZN(_078_)
  );
  AOI21_X2 _171_ (
    .A(_077_),
    .B1(_073_),
    .B2(_075_),
    .ZN(_079_)
  );
  NAND2_X1 _172_ (
    .A1(_136_),
    .A2(_135_),
    .ZN(_080_)
  );
  NOR3_X2 _173_ (
    .A1(_078_),
    .A2(_079_),
    .A3(_080_),
    .ZN(_081_)
  );
  INV_X1 _174_ (
    .A(_080_),
    .ZN(_082_)
  );
  NAND2_X2 _175_ (
    .A1(_073_),
    .A2(_075_),
    .ZN(_083_)
  );
  NAND2_X2 _176_ (
    .A1(_083_),
    .A2(_076_),
    .ZN(_084_)
  );
  NAND3_X2 _177_ (
    .A1(_073_),
    .A2(_075_),
    .A3(_077_),
    .ZN(_085_)
  );
  AOI21_X1 _178_ (
    .A(_082_),
    .B1(_084_),
    .B2(_085_),
    .ZN(_086_)
  );
  OAI21_X1 _179_ (
    .A(_070_),
    .B1(_081_),
    .B2(_086_),
    .ZN(_087_)
  );
  NAND3_X1 _180_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_082_),
    .ZN(_088_)
  );
  OAI21_X2 _181_ (
    .A(_080_),
    .B1(_078_),
    .B2(_079_),
    .ZN(_089_)
  );
  INV_X1 _182_ (
    .A(_070_),
    .ZN(_090_)
  );
  NAND3_X1 _183_ (
    .A1(_088_),
    .A2(_089_),
    .A3(_090_),
    .ZN(_091_)
  );
  NAND2_X1 _184_ (
    .A1(_087_),
    .A2(_091_),
    .ZN(_092_)
  );
  NOR3_X1 _185_ (
    .A1(_067_),
    .A2(_056_),
    .A3(_057_),
    .ZN(_093_)
  );
  XOR2_X1 _186_ (
    .A(_092_),
    .B(_093_),
    .Z(_002_)
  );
  AOI21_X1 _187_ (
    .A(_067_),
    .B1(_087_),
    .B2(_091_),
    .ZN(_094_)
  );
  NAND2_X1 _188_ (
    .A1(_094_),
    .A2(_068_),
    .ZN(_095_)
  );
  INV_X1 _189_ (
    .A(_095_),
    .ZN(_096_)
  );
  NAND2_X1 _190_ (
    .A1(_083_),
    .A2(_077_),
    .ZN(_097_)
  );
  NOR2_X1 _191_ (
    .A1(_071_),
    .A2(_074_),
    .ZN(_098_)
  );
  INV_X1 _192_ (
    .A(_098_),
    .ZN(_099_)
  );
  NAND2_X1 _193_ (
    .A1(_059_),
    .A2(_064_),
    .ZN(_100_)
  );
  NAND3_X2 _194_ (
    .A1(_100_),
    .A2(_072_),
    .A3(_055_),
    .ZN(_101_)
  );
  NAND2_X2 _195_ (
    .A1(_072_),
    .A2(_055_),
    .ZN(_102_)
  );
  NAND3_X2 _196_ (
    .A1(_102_),
    .A2(_059_),
    .A3(_064_),
    .ZN(_103_)
  );
  NAND2_X1 _197_ (
    .A1(_137_),
    .A2(_135_),
    .ZN(_104_)
  );
  INV_X1 _198_ (
    .A(_104_),
    .ZN(_105_)
  );
  NAND3_X1 _199_ (
    .A1(_101_),
    .A2(_103_),
    .A3(_105_),
    .ZN(_106_)
  );
  INV_X1 _200_ (
    .A(_106_),
    .ZN(_107_)
  );
  AOI21_X1 _201_ (
    .A(_105_),
    .B1(_101_),
    .B2(_103_),
    .ZN(_108_)
  );
  OAI211_X1 _202_ (
    .A(_097_),
    .B(_099_),
    .C1(_107_),
    .C2(_108_),
    .ZN(_109_)
  );
  NAND2_X1 _203_ (
    .A1(_101_),
    .A2(_103_),
    .ZN(_110_)
  );
  NAND2_X1 _204_ (
    .A1(_110_),
    .A2(_104_),
    .ZN(_111_)
  );
  AOI21_X1 _205_ (
    .A(_076_),
    .B1(_073_),
    .B2(_075_),
    .ZN(_112_)
  );
  OAI211_X1 _206_ (
    .A(_111_),
    .B(_106_),
    .C1(_112_),
    .C2(_098_),
    .ZN(_113_)
  );
  AND2_X1 _207_ (
    .A1(_109_),
    .A2(_113_),
    .ZN(_114_)
  );
  AOI21_X2 _208_ (
    .A(_070_),
    .B1(_089_),
    .B2(_088_),
    .ZN(_115_)
  );
  AOI21_X2 _209_ (
    .A(_080_),
    .B1(_084_),
    .B2(_085_),
    .ZN(_116_)
  );
  NOR3_X2 _210_ (
    .A1(_114_),
    .A2(_115_),
    .A3(_116_),
    .ZN(_117_)
  );
  NAND2_X1 _211_ (
    .A1(_109_),
    .A2(_113_),
    .ZN(_118_)
  );
  OAI21_X1 _212_ (
    .A(_090_),
    .B1(_081_),
    .B2(_086_),
    .ZN(_119_)
  );
  INV_X1 _213_ (
    .A(_116_),
    .ZN(_120_)
  );
  AOI21_X2 _214_ (
    .A(_118_),
    .B1(_119_),
    .B2(_120_),
    .ZN(_121_)
  );
  NOR2_X2 _215_ (
    .A1(_117_),
    .A2(_121_),
    .ZN(_122_)
  );
  XNOR2_X1 _216_ (
    .A(_096_),
    .B(_122_),
    .ZN(_003_)
  );
  OAI21_X2 _217_ (
    .A(_118_),
    .B1(_115_),
    .B2(_116_),
    .ZN(_123_)
  );
  OAI21_X2 _218_ (
    .A(_123_),
    .B1(_122_),
    .B2(_095_),
    .ZN(_124_)
  );
  NAND2_X1 _219_ (
    .A1(_097_),
    .A2(_099_),
    .ZN(_125_)
  );
  NAND2_X1 _220_ (
    .A1(_110_),
    .A2(_105_),
    .ZN(_126_)
  );
  NAND2_X1 _221_ (
    .A1(_059_),
    .A2(_135_),
    .ZN(_127_)
  );
  NAND3_X2 _222_ (
    .A1(_127_),
    .A2(_072_),
    .A3(_064_),
    .ZN(_128_)
  );
  NAND2_X2 _223_ (
    .A1(_072_),
    .A2(_064_),
    .ZN(_129_)
  );
  NAND3_X2 _224_ (
    .A1(_129_),
    .A2(_059_),
    .A3(_135_),
    .ZN(_130_)
  );
  AND4_X4 _225_ (
    .A1(_059_),
    .A2(_072_),
    .A3(_055_),
    .A4(_064_),
    .ZN(_131_)
  );
  AND3_X4 _226_ (
    .A1(_128_),
    .A2(_130_),
    .A3(_131_),
    .ZN(_008_)
  );
  AOI21_X1 _227_ (
    .A(_131_),
    .B1(_128_),
    .B2(_130_),
    .ZN(_009_)
  );
  OAI21_X2 _228_ (
    .A(_126_),
    .B1(_008_),
    .B2(_009_),
    .ZN(_010_)
  );
  NAND2_X1 _229_ (
    .A1(_128_),
    .A2(_130_),
    .ZN(_011_)
  );
  INV_X1 _230_ (
    .A(_131_),
    .ZN(_012_)
  );
  NAND2_X2 _231_ (
    .A1(_011_),
    .A2(_012_),
    .ZN(_013_)
  );
  AOI21_X2 _232_ (
    .A(_104_),
    .B1(_101_),
    .B2(_103_),
    .ZN(_014_)
  );
  NAND3_X1 _233_ (
    .A1(_128_),
    .A2(_130_),
    .A3(_131_),
    .ZN(_015_)
  );
  NAND3_X2 _234_ (
    .A1(_013_),
    .A2(_014_),
    .A3(_015_),
    .ZN(_016_)
  );
  NAND2_X1 _235_ (
    .A1(_111_),
    .A2(_106_),
    .ZN(_017_)
  );
  AND4_X2 _236_ (
    .A1(_125_),
    .A2(_010_),
    .A3(_016_),
    .A4(_017_),
    .ZN(_018_)
  );
  AOI22_X2 _237_ (
    .A1(_010_),
    .A2(_016_),
    .B1(_017_),
    .B2(_125_),
    .ZN(_019_)
  );
  NOR2_X2 _238_ (
    .A1(_018_),
    .A2(_019_),
    .ZN(_020_)
  );
  XNOR2_X2 _239_ (
    .A(_124_),
    .B(_020_),
    .ZN(_004_)
  );
  NAND2_X1 _240_ (
    .A1(_017_),
    .A2(_125_),
    .ZN(_021_)
  );
  AOI21_X1 _241_ (
    .A(_021_),
    .B1(_010_),
    .B2(_016_),
    .ZN(_022_)
  );
  INV_X1 _242_ (
    .A(_123_),
    .ZN(_023_)
  );
  INV_X1 _243_ (
    .A(_021_),
    .ZN(_024_)
  );
  NAND3_X1 _244_ (
    .A1(_024_),
    .A2(_010_),
    .A3(_016_),
    .ZN(_025_)
  );
  INV_X2 _245_ (
    .A(_019_),
    .ZN(_026_)
  );
  NAND2_X2 _246_ (
    .A1(_025_),
    .A2(_026_),
    .ZN(_027_)
  );
  AOI21_X1 _247_ (
    .A(_022_),
    .B1(_023_),
    .B2(_027_),
    .ZN(_028_)
  );
  OAI21_X1 _248_ (
    .A(_027_),
    .B1(_117_),
    .B2(_121_),
    .ZN(_029_)
  );
  OAI21_X2 _249_ (
    .A(_028_),
    .B1(_029_),
    .B2(_095_),
    .ZN(_030_)
  );
  NAND2_X1 _250_ (
    .A1(_011_),
    .A2(_131_),
    .ZN(_031_)
  );
  OR2_X1 _251_ (
    .A1(_127_),
    .A2(_129_),
    .ZN(_032_)
  );
  NAND2_X1 _252_ (
    .A1(_031_),
    .A2(_032_),
    .ZN(_033_)
  );
  NAND2_X1 _253_ (
    .A1(_072_),
    .A2(_135_),
    .ZN(_034_)
  );
  XNOR2_X1 _254_ (
    .A(_033_),
    .B(_034_),
    .ZN(_035_)
  );
  NAND2_X1 _255_ (
    .A1(_013_),
    .A2(_015_),
    .ZN(_036_)
  );
  NAND2_X1 _256_ (
    .A1(_036_),
    .A2(_014_),
    .ZN(_037_)
  );
  INV_X1 _257_ (
    .A(_037_),
    .ZN(_038_)
  );
  XNOR2_X1 _258_ (
    .A(_035_),
    .B(_038_),
    .ZN(_039_)
  );
  NAND2_X1 _259_ (
    .A1(_030_),
    .A2(_039_),
    .ZN(_040_)
  );
  INV_X1 _260_ (
    .A(_022_),
    .ZN(_041_)
  );
  OAI21_X2 _261_ (
    .A(_041_),
    .B1(_020_),
    .B2(_123_),
    .ZN(_042_)
  );
  OAI21_X1 _262_ (
    .A(_114_),
    .B1(_115_),
    .B2(_116_),
    .ZN(_043_)
  );
  NAND3_X1 _263_ (
    .A1(_119_),
    .A2(_120_),
    .A3(_118_),
    .ZN(_044_)
  );
  AOI22_X2 _264_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_025_),
    .B2(_026_),
    .ZN(_045_)
  );
  AOI21_X2 _265_ (
    .A(_042_),
    .B1(_096_),
    .B2(_045_),
    .ZN(_046_)
  );
  INV_X1 _266_ (
    .A(_039_),
    .ZN(_047_)
  );
  NAND2_X1 _267_ (
    .A1(_046_),
    .A2(_047_),
    .ZN(_048_)
  );
  NAND2_X2 _268_ (
    .A1(_040_),
    .A2(_048_),
    .ZN(_005_)
  );
  AOI21_X1 _269_ (
    .A(_034_),
    .B1(_031_),
    .B2(_032_),
    .ZN(_049_)
  );
  AOI21_X1 _270_ (
    .A(_049_),
    .B1(_035_),
    .B2(_038_),
    .ZN(_050_)
  );
  INV_X1 _271_ (
    .A(_050_),
    .ZN(_051_)
  );
  OAI21_X2 _272_ (
    .A(_051_),
    .B1(_046_),
    .B2(_039_),
    .ZN(_052_)
  );
  NAND3_X1 _273_ (
    .A1(_030_),
    .A2(_047_),
    .A3(_050_),
    .ZN(_053_)
  );
  NAND2_X2 _274_ (
    .A1(_052_),
    .A2(_053_),
    .ZN(_006_)
  );
  assign a = { \fa4.cy , \add.grey6.pik , \ha3.s , \ha2.s , \add.black3_2.pik , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.a  = { \fa4.cy , \add.grey6.pik , \ha3.s , \ha2.s , \add.black3_2.pik , \add.black3_2.pkj , ip_0_1, ip_0_0 };
  assign \add.b  = { 2'h0, \ha2.c , \fa2.cy , 2'h0, ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = 1'h0;
  assign \add.black3_2.gik  = 1'h0;
  assign \add.black3_2.gkj  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = 1'h0;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = 1'h0;
  assign \add.g3_3  = 1'h0;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = \add.black5_4.gkj ;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = \add.black5_4.gij ;
  assign \add.g5_5  = \add.black5_4.gik ;
  assign \add.g6_0  = \add.c6 ;
  assign \add.g6_6  = 1'h0;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = 1'h0;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gik  = 1'h0;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = \add.black5_4.gkj ;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gik  = \add.black5_4.gij ;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = 1'h0;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \ha2.c , \fa2.cy , 2'h0, ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pkj ;
  assign \fa0.sm  = \add.black3_2.pkj ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa1.h2.b ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.sm  = \fa1.h2.s ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa1.h2.s ;
  assign \fa2.c  = \fa0.cy ;
  assign \fa2.h1.b  = \fa1.h2.s ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.h2.b  = \fa0.cy ;
  assign \fa2.h2.s  = \add.black3_2.pik ;
  assign \fa2.sm  = \add.black3_2.pik ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa3.h1.a ;
  assign \fa3.b  = \fa3.h1.b ;
  assign \fa3.c  = \fa3.h2.b ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.sm  = \fa3.h2.s ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa3.cy ;
  assign \fa4.c  = \fa4.h2.b ;
  assign \fa4.h1.b  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.h2.s  = \add.grey6.pik ;
  assign \fa4.sm  = \add.grey6.pik ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \ha0.c  = \fa3.h2.b ;
  assign \ha1.b  = \ha0.s ;
  assign \ha2.a  = \ha1.s ;
  assign \ha2.b  = \fa1.cy ;
  assign \ha3.a  = \fa3.h2.s ;
  assign \ha3.b  = \ha1.c ;
  assign \ha3.c  = \fa4.h2.b ;
  assign ip_0_2 = \fa0.h1.a ;
  assign ip_0_3 = \fa1.h1.a ;
  assign ip_1_1 = \fa0.h1.b ;
  assign ip_1_2 = \fa1.h1.b ;
  assign ip_1_3 = \ha0.a ;
  assign ip_2_0 = \fa0.h2.b ;
  assign ip_2_1 = \fa1.h2.b ;
  assign ip_2_2 = \ha0.b ;
  assign ip_2_3 = \fa3.h1.a ;
  assign ip_3_0 = \fa2.h1.a ;
  assign ip_3_1 = \ha1.a ;
  assign ip_3_2 = \fa3.h1.b ;
  assign ip_3_3 = \fa4.h1.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.cy ;
  assign p1 = \add.black3_2.pkj ;
  assign p10 = \ha2.c ;
  assign p11 = \ha2.s ;
  assign p12 = \fa3.cy ;
  assign p13 = \fa3.h2.s ;
  assign p14 = \fa4.h2.b ;
  assign p15 = \ha3.s ;
  assign p16 = \fa4.cy ;
  assign p17 = \add.grey6.pik ;
  assign p2 = \fa1.cy ;
  assign p3 = \fa1.h2.s ;
  assign p4 = \fa2.cy ;
  assign p5 = \add.black3_2.pik ;
  assign p6 = \fa3.h2.b ;
  assign p7 = \ha0.s ;
  assign p8 = \ha1.c ;
  assign p9 = \ha1.s ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _136_ = y[0];
  assign _132_ = x[0];
  assign ip_0_0 = _007_;
  assign _137_ = y[1];
  assign _138_ = y[2];
  assign _139_ = y[3];
  assign _133_ = x[1];
  assign _134_ = x[2];
  assign _135_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
