/* Generated by Yosys 0.43+3 (git sha1 b08688f71, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "main" *)
(* top =  1  *)
(* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:3.1-65.10" *)
module main(x, y, o);
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.82-93.86" *)
  wire _000_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _001_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _002_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _003_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _004_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _005_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire _006_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.6-6.12" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.13-4.14" *)
  wire _076_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.13-4.14" *)
  wire _077_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.13-4.14" *)
  wire _078_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.13-4.14" *)
  wire _079_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.15-4.16" *)
  wire _080_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.15-4.16" *)
  wire _081_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.15-4.16" *)
  wire _082_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.15-4.16" *)
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:37.12-37.13" *)
  wire [7:0] a;
  (* hdlname = "add a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:91.13-91.14" *)
  wire [7:0] \add.a ;
  (* hdlname = "add b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:91.15-91.16" *)
  wire [7:0] \add.b ;
  (* hdlname = "add black3_2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:148.8-148.11" *)
  wire \add.black3_2.gij ;
  (* hdlname = "add black3_2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.7-147.10" *)
  wire \add.black3_2.gik ;
  (* hdlname = "add black3_2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.17-147.20" *)
  wire \add.black3_2.gkj ;
  (* hdlname = "add black3_2 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:148.13-148.16" *)
  wire \add.black3_2.pij ;
  (* hdlname = "add black3_2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.12-147.15" *)
  wire \add.black3_2.pik ;
  (* hdlname = "add black3_2 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.22-147.25" *)
  wire \add.black3_2.pkj ;
  (* hdlname = "add black5_4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:148.8-148.11" *)
  wire \add.black5_4.gij ;
  (* hdlname = "add black5_4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.7-147.10" *)
  wire \add.black5_4.gik ;
  (* hdlname = "add black5_4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.17-147.20" *)
  wire \add.black5_4.gkj ;
  (* hdlname = "add black5_4 pij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:148.13-148.16" *)
  wire \add.black5_4.pij ;
  (* hdlname = "add black5_4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.12-147.15" *)
  wire \add.black5_4.pik ;
  (* hdlname = "add black5_4 pkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:147.22-147.25" *)
  wire \add.black5_4.pkj ;
  (* hdlname = "add c0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.46-93.48" *)
  wire \add.c0 ;
  (* hdlname = "add c1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.144-93.146" *)
  wire \add.c1 ;
  (* hdlname = "add c2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.54-93.56" *)
  wire \add.c2 ;
  (* hdlname = "add c3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.162-93.164" *)
  wire \add.c3 ;
  (* hdlname = "add c4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.126-93.128" *)
  wire \add.c4 ;
  (* hdlname = "add c5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.90-93.92" *)
  wire \add.c5 ;
  (* hdlname = "add c6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.123-93.125" *)
  wire \add.c6 ;
  (* hdlname = "add g0_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.49-93.53" *)
  wire \add.g0_0 ;
  (* hdlname = "add g1_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.67-93.71" *)
  wire \add.g1_0 ;
  (* hdlname = "add g1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.77-93.81" *)
  wire \add.g1_1 ;
  (* hdlname = "add g2_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:112.8-112.12" *)
  wire \add.g2_0 ;
  (* hdlname = "add g2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.62-93.66" *)
  wire \add.g2_2 ;
  (* hdlname = "add g3_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.16-93.20" *)
  wire \add.g3_0 ;
  (* hdlname = "add g3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.11-93.15" *)
  wire \add.g3_2 ;
  (* hdlname = "add g3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.36-93.40" *)
  wire \add.g3_3 ;
  (* hdlname = "add g4_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:114.8-114.12" *)
  wire \add.g4_0 ;
  (* hdlname = "add g4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.72-93.76" *)
  wire \add.g4_4 ;
  (* hdlname = "add g5_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.93-93.97" *)
  wire \add.g5_0 ;
  (* hdlname = "add g5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.118-93.122" *)
  wire \add.g5_4 ;
  (* hdlname = "add g5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.21-93.25" *)
  wire \add.g5_5 ;
  (* hdlname = "add g6_0" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:116.8-116.12" *)
  wire \add.g6_0 ;
  (* hdlname = "add g6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.147-93.151" *)
  wire \add.g6_6 ;
  (* hdlname = "add grey1 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey1.gij ;
  (* hdlname = "add grey1 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey1.gik ;
  (* hdlname = "add grey1 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey1.gkj ;
  (* hdlname = "add grey1 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey1.pik ;
  (* hdlname = "add grey2 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey2.gij ;
  (* hdlname = "add grey2 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey2.gik ;
  (* hdlname = "add grey2 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey2.gkj ;
  (* hdlname = "add grey2 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey2.pik ;
  (* hdlname = "add grey3 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey3.gij ;
  (* hdlname = "add grey3 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey3.gik ;
  (* hdlname = "add grey3 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey3.gkj ;
  (* hdlname = "add grey3 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey3.pik ;
  (* hdlname = "add grey4 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey4.gij ;
  (* hdlname = "add grey4 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey4.gik ;
  (* hdlname = "add grey4 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey4.gkj ;
  (* hdlname = "add grey4 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey4.pik ;
  (* hdlname = "add grey5 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey5.gij ;
  (* hdlname = "add grey5 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey5.gik ;
  (* hdlname = "add grey5 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey5.gkj ;
  (* hdlname = "add grey5 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey5.pik ;
  (* hdlname = "add grey6 gij" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:142.8-142.11" *)
  wire \add.grey6.gij ;
  (* hdlname = "add grey6 gik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.7-141.10" *)
  wire \add.grey6.gik ;
  (* hdlname = "add grey6 gkj" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.17-141.20" *)
  wire \add.grey6.gkj ;
  (* hdlname = "add grey6 pik" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:141.12-141.15" *)
  wire \add.grey6.pik ;
  (* hdlname = "add p1_1" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.82-93.86" *)
  wire \add.p1_1 ;
  (* hdlname = "add p2_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.26-93.30" *)
  wire \add.p2_2 ;
  (* hdlname = "add p3_2" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.41-93.45" *)
  wire \add.p3_2 ;
  (* hdlname = "add p3_3" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.98-93.102" *)
  wire \add.p3_3 ;
  (* hdlname = "add p4_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.103-93.107" *)
  wire \add.p4_4 ;
  (* hdlname = "add p5_4" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.31-93.35" *)
  wire \add.p5_4 ;
  (* hdlname = "add p5_5" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.6-93.10" *)
  wire \add.p5_5 ;
  (* hdlname = "add p6_6" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:93.108-93.112" *)
  wire \add.p6_6 ;
  (* hdlname = "add s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:92.14-92.15" *)
  wire [7:0] \add.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:37.14-37.15" *)
  wire [7:0] b;
  (* hdlname = "fa0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.7-74.8" *)
  wire \fa0.a ;
  (* hdlname = "fa0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.9-74.10" *)
  wire \fa0.b ;
  (* hdlname = "fa0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.11-74.12" *)
  wire \fa0.c ;
  (* hdlname = "fa0 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.8-75.10" *)
  wire \fa0.cy ;
  (* hdlname = "fa0 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa0.h1.a ;
  (* hdlname = "fa0 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa0.h1.b ;
  (* hdlname = "fa0 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa0.h1.c ;
  (* hdlname = "fa0 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa0.h1.s ;
  (* hdlname = "fa0 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa0.h2.a ;
  (* hdlname = "fa0 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa0.h2.b ;
  (* hdlname = "fa0 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa0.h2.c ;
  (* hdlname = "fa0 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa0.h2.s ;
  (* hdlname = "fa0 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.11-75.13" *)
  wire \fa0.sm ;
  (* hdlname = "fa0 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.6-76.7" *)
  wire \fa0.x ;
  (* hdlname = "fa0 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.8-76.9" *)
  wire \fa0.y ;
  (* hdlname = "fa0 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.10-76.11" *)
  wire \fa0.z ;
  (* hdlname = "fa1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.7-74.8" *)
  wire \fa1.a ;
  (* hdlname = "fa1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.9-74.10" *)
  wire \fa1.b ;
  (* hdlname = "fa1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.11-74.12" *)
  wire \fa1.c ;
  (* hdlname = "fa1 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.8-75.10" *)
  wire \fa1.cy ;
  (* hdlname = "fa1 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa1.h1.a ;
  (* hdlname = "fa1 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa1.h1.b ;
  (* hdlname = "fa1 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa1.h1.c ;
  (* hdlname = "fa1 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa1.h1.s ;
  (* hdlname = "fa1 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa1.h2.a ;
  (* hdlname = "fa1 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa1.h2.b ;
  (* hdlname = "fa1 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa1.h2.c ;
  (* hdlname = "fa1 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa1.h2.s ;
  (* hdlname = "fa1 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.11-75.13" *)
  wire \fa1.sm ;
  (* hdlname = "fa1 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.6-76.7" *)
  wire \fa1.x ;
  (* hdlname = "fa1 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.8-76.9" *)
  wire \fa1.y ;
  (* hdlname = "fa1 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.10-76.11" *)
  wire \fa1.z ;
  (* hdlname = "fa2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.7-74.8" *)
  wire \fa2.a ;
  (* hdlname = "fa2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.9-74.10" *)
  wire \fa2.b ;
  (* hdlname = "fa2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.11-74.12" *)
  wire \fa2.c ;
  (* hdlname = "fa2 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.8-75.10" *)
  wire \fa2.cy ;
  (* hdlname = "fa2 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa2.h1.a ;
  (* hdlname = "fa2 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa2.h1.b ;
  (* hdlname = "fa2 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa2.h1.c ;
  (* hdlname = "fa2 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa2.h1.s ;
  (* hdlname = "fa2 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa2.h2.a ;
  (* hdlname = "fa2 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa2.h2.b ;
  (* hdlname = "fa2 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa2.h2.c ;
  (* hdlname = "fa2 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa2.h2.s ;
  (* hdlname = "fa2 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.11-75.13" *)
  wire \fa2.sm ;
  (* hdlname = "fa2 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.6-76.7" *)
  wire \fa2.x ;
  (* hdlname = "fa2 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.8-76.9" *)
  wire \fa2.y ;
  (* hdlname = "fa2 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.10-76.11" *)
  wire \fa2.z ;
  (* hdlname = "fa3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.7-74.8" *)
  wire \fa3.a ;
  (* hdlname = "fa3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.9-74.10" *)
  wire \fa3.b ;
  (* hdlname = "fa3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.11-74.12" *)
  wire \fa3.c ;
  (* hdlname = "fa3 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.8-75.10" *)
  wire \fa3.cy ;
  (* hdlname = "fa3 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa3.h1.a ;
  (* hdlname = "fa3 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa3.h1.b ;
  (* hdlname = "fa3 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa3.h1.c ;
  (* hdlname = "fa3 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa3.h1.s ;
  (* hdlname = "fa3 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa3.h2.a ;
  (* hdlname = "fa3 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa3.h2.b ;
  (* hdlname = "fa3 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa3.h2.c ;
  (* hdlname = "fa3 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa3.h2.s ;
  (* hdlname = "fa3 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.11-75.13" *)
  wire \fa3.sm ;
  (* hdlname = "fa3 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.6-76.7" *)
  wire \fa3.x ;
  (* hdlname = "fa3 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.8-76.9" *)
  wire \fa3.y ;
  (* hdlname = "fa3 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.10-76.11" *)
  wire \fa3.z ;
  (* hdlname = "fa4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.7-74.8" *)
  wire \fa4.a ;
  (* hdlname = "fa4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.9-74.10" *)
  wire \fa4.b ;
  (* hdlname = "fa4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:74.11-74.12" *)
  wire \fa4.c ;
  (* hdlname = "fa4 cy" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.8-75.10" *)
  wire \fa4.cy ;
  (* hdlname = "fa4 h1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa4.h1.a ;
  (* hdlname = "fa4 h1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa4.h1.b ;
  (* hdlname = "fa4 h1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa4.h1.c ;
  (* hdlname = "fa4 h1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa4.h1.s ;
  (* hdlname = "fa4 h2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \fa4.h2.a ;
  (* hdlname = "fa4 h2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \fa4.h2.b ;
  (* hdlname = "fa4 h2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \fa4.h2.c ;
  (* hdlname = "fa4 h2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \fa4.h2.s ;
  (* hdlname = "fa4 sm" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:75.11-75.13" *)
  wire \fa4.sm ;
  (* hdlname = "fa4 x" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.6-76.7" *)
  wire \fa4.x ;
  (* hdlname = "fa4 y" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.8-76.9" *)
  wire \fa4.y ;
  (* hdlname = "fa4 z" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:76.10-76.11" *)
  wire \fa4.z ;
  (* hdlname = "ha0 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha0.a ;
  (* hdlname = "ha0 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha0.b ;
  (* hdlname = "ha0 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha0.c ;
  (* hdlname = "ha0 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha0.s ;
  (* hdlname = "ha1 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha1.a ;
  (* hdlname = "ha1 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha1.b ;
  (* hdlname = "ha1 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha1.c ;
  (* hdlname = "ha1 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha1.s ;
  (* hdlname = "ha2 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha2.a ;
  (* hdlname = "ha2 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha2.b ;
  (* hdlname = "ha2 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha2.c ;
  (* hdlname = "ha2 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha2.s ;
  (* hdlname = "ha3 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha3.a ;
  (* hdlname = "ha3 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha3.b ;
  (* hdlname = "ha3 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha3.c ;
  (* hdlname = "ha3 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha3.s ;
  (* hdlname = "ha4 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha4.a ;
  (* hdlname = "ha4 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha4.b ;
  (* hdlname = "ha4 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha4.c ;
  (* hdlname = "ha4 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha4.s ;
  (* hdlname = "ha5 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha5.a ;
  (* hdlname = "ha5 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha5.b ;
  (* hdlname = "ha5 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha5.c ;
  (* hdlname = "ha5 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha5.s ;
  (* hdlname = "ha6 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha6.a ;
  (* hdlname = "ha6 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha6.b ;
  (* hdlname = "ha6 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha6.c ;
  (* hdlname = "ha6 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha6.s ;
  (* hdlname = "ha7 a" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.7-68.8" *)
  wire \ha7.a ;
  (* hdlname = "ha7 b" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:68.9-68.10" *)
  wire \ha7.b ;
  (* hdlname = "ha7 c" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.8-69.9" *)
  wire \ha7.c ;
  (* hdlname = "ha7 s" *)
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:69.10-69.11" *)
  wire \ha7.s ;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.6-6.12" *)
  wire ip_0_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.13-6.19" *)
  wire ip_0_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.20-6.26" *)
  wire ip_0_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.27-6.33" *)
  wire ip_0_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.34-6.40" *)
  wire ip_1_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.41-6.47" *)
  wire ip_1_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.48-6.54" *)
  wire ip_1_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.55-6.61" *)
  wire ip_1_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.62-6.68" *)
  wire ip_2_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.69-6.75" *)
  wire ip_2_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.76-6.82" *)
  wire ip_2_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.83-6.89" *)
  wire ip_2_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.90-6.96" *)
  wire ip_3_0;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.97-6.103" *)
  wire ip_3_1;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.104-6.110" *)
  wire ip_3_2;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:6.111-6.117" *)
  wire ip_3_3;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:5.14-5.15" *)
  output [7:0] o;
  wire [7:0] o;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.6-7.8" *)
  wire p0;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.9-7.11" *)
  wire p1;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.36-7.39" *)
  wire p10;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.40-7.43" *)
  wire p11;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.44-7.47" *)
  wire p12;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.48-7.51" *)
  wire p13;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.52-7.55" *)
  wire p14;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.56-7.59" *)
  wire p15;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.60-7.63" *)
  wire p16;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.64-7.67" *)
  wire p17;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.68-7.71" *)
  wire p18;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.72-7.75" *)
  wire p19;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.12-7.14" *)
  wire p2;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.76-7.79" *)
  wire p20;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.80-7.83" *)
  wire p21;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.84-7.87" *)
  wire p22;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.88-7.91" *)
  wire p23;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.92-7.95" *)
  wire p24;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.96-7.99" *)
  wire p25;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.15-7.17" *)
  wire p3;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.18-7.20" *)
  wire p4;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.21-7.23" *)
  wire p5;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.24-7.26" *)
  wire p6;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.27-7.29" *)
  wire p7;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.30-7.32" *)
  wire p8;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:7.33-7.35" *)
  wire p9;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:38.12-38.13" *)
  wire [7:0] s;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.13-4.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "run_verilog_mult_mid/multiplier_4b_bcef06ccb3bac9a24cefc603ca43b7ca.v:4.15-4.16" *)
  input [3:0] y;
  wire [3:0] y;
  AND2_X1 _087_ (
    .A1(_080_),
    .A2(_076_),
    .ZN(_007_)
  );
  NAND2_X1 _088_ (
    .A1(_080_),
    .A2(_077_),
    .ZN(_008_)
  );
  NAND2_X1 _089_ (
    .A1(_076_),
    .A2(_081_),
    .ZN(_009_)
  );
  XOR2_X1 _090_ (
    .A(_008_),
    .B(_009_),
    .Z(_000_)
  );
  NAND2_X1 _091_ (
    .A1(_081_),
    .A2(_077_),
    .ZN(_010_)
  );
  NAND2_X1 _092_ (
    .A1(_076_),
    .A2(_082_),
    .ZN(_011_)
  );
  XOR2_X1 _093_ (
    .A(_010_),
    .B(_011_),
    .Z(_012_)
  );
  AND2_X1 _094_ (
    .A1(_080_),
    .A2(_078_),
    .ZN(_013_)
  );
  XNOR2_X1 _095_ (
    .A(_012_),
    .B(_013_),
    .ZN(_014_)
  );
  NOR2_X1 _096_ (
    .A1(_008_),
    .A2(_009_),
    .ZN(_015_)
  );
  XNOR2_X1 _097_ (
    .A(_014_),
    .B(_015_),
    .ZN(_001_)
  );
  NAND2_X1 _098_ (
    .A1(_082_),
    .A2(_077_),
    .ZN(_016_)
  );
  NAND2_X1 _099_ (
    .A1(_076_),
    .A2(_083_),
    .ZN(_017_)
  );
  XNOR2_X1 _100_ (
    .A(_016_),
    .B(_017_),
    .ZN(_018_)
  );
  NOR2_X1 _101_ (
    .A1(_010_),
    .A2(_011_),
    .ZN(_019_)
  );
  XNOR2_X1 _102_ (
    .A(_018_),
    .B(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _103_ (
    .A1(_080_),
    .A2(_079_),
    .ZN(_021_)
  );
  NAND2_X1 _104_ (
    .A1(_081_),
    .A2(_078_),
    .ZN(_022_)
  );
  XOR2_X1 _105_ (
    .A(_021_),
    .B(_022_),
    .Z(_023_)
  );
  XNOR2_X1 _106_ (
    .A(_020_),
    .B(_023_),
    .ZN(_024_)
  );
  NAND2_X1 _107_ (
    .A1(_012_),
    .A2(_013_),
    .ZN(_025_)
  );
  INV_X1 _108_ (
    .A(_015_),
    .ZN(_026_)
  );
  OAI21_X1 _109_ (
    .A(_025_),
    .B1(_014_),
    .B2(_026_),
    .ZN(_027_)
  );
  XNOR2_X1 _110_ (
    .A(_024_),
    .B(_027_),
    .ZN(_002_)
  );
  OR2_X1 _111_ (
    .A1(_024_),
    .A2(_014_),
    .ZN(_028_)
  );
  OAI22_X1 _112_ (
    .A1(_028_),
    .A2(_026_),
    .B1(_024_),
    .B2(_025_),
    .ZN(_029_)
  );
  NAND2_X1 _113_ (
    .A1(_082_),
    .A2(_078_),
    .ZN(_030_)
  );
  NAND2_X1 _114_ (
    .A1(_083_),
    .A2(_077_),
    .ZN(_031_)
  );
  XOR2_X1 _115_ (
    .A(_030_),
    .B(_031_),
    .Z(_032_)
  );
  NOR2_X1 _116_ (
    .A1(_021_),
    .A2(_022_),
    .ZN(_033_)
  );
  XNOR2_X1 _117_ (
    .A(_032_),
    .B(_033_),
    .ZN(_034_)
  );
  NOR2_X1 _118_ (
    .A1(_016_),
    .A2(_017_),
    .ZN(_035_)
  );
  NAND2_X1 _119_ (
    .A1(_081_),
    .A2(_079_),
    .ZN(_036_)
  );
  XNOR2_X1 _120_ (
    .A(_035_),
    .B(_036_),
    .ZN(_037_)
  );
  XNOR2_X1 _121_ (
    .A(_034_),
    .B(_037_),
    .ZN(_038_)
  );
  NOR3_X1 _122_ (
    .A1(_018_),
    .A2(_010_),
    .A3(_011_),
    .ZN(_039_)
  );
  AOI21_X1 _123_ (
    .A(_039_),
    .B1(_020_),
    .B2(_023_),
    .ZN(_040_)
  );
  XNOR2_X1 _124_ (
    .A(_038_),
    .B(_040_),
    .ZN(_041_)
  );
  XOR2_X1 _125_ (
    .A(_029_),
    .B(_041_),
    .Z(_003_)
  );
  INV_X1 _126_ (
    .A(_040_),
    .ZN(_042_)
  );
  NAND2_X1 _127_ (
    .A1(_038_),
    .A2(_042_),
    .ZN(_043_)
  );
  INV_X1 _128_ (
    .A(_034_),
    .ZN(_044_)
  );
  NAND2_X1 _129_ (
    .A1(_044_),
    .A2(_037_),
    .ZN(_045_)
  );
  NAND2_X1 _130_ (
    .A1(_043_),
    .A2(_045_),
    .ZN(_046_)
  );
  NAND2_X1 _131_ (
    .A1(_032_),
    .A2(_033_),
    .ZN(_047_)
  );
  NOR3_X1 _132_ (
    .A1(_016_),
    .A2(_017_),
    .A3(_036_),
    .ZN(_048_)
  );
  XNOR2_X1 _133_ (
    .A(_047_),
    .B(_048_),
    .ZN(_049_)
  );
  NAND2_X1 _134_ (
    .A1(_082_),
    .A2(_079_),
    .ZN(_050_)
  );
  NAND2_X1 _135_ (
    .A1(_083_),
    .A2(_078_),
    .ZN(_051_)
  );
  XNOR2_X1 _136_ (
    .A(_050_),
    .B(_051_),
    .ZN(_052_)
  );
  NOR2_X1 _137_ (
    .A1(_030_),
    .A2(_031_),
    .ZN(_053_)
  );
  XNOR2_X1 _138_ (
    .A(_052_),
    .B(_053_),
    .ZN(_054_)
  );
  XOR2_X1 _139_ (
    .A(_049_),
    .B(_054_),
    .Z(_055_)
  );
  XNOR2_X1 _140_ (
    .A(_046_),
    .B(_055_),
    .ZN(_056_)
  );
  NAND2_X1 _141_ (
    .A1(_029_),
    .A2(_041_),
    .ZN(_057_)
  );
  XOR2_X1 _142_ (
    .A(_056_),
    .B(_057_),
    .Z(_004_)
  );
  INV_X1 _143_ (
    .A(_056_),
    .ZN(_058_)
  );
  AND2_X1 _144_ (
    .A1(_058_),
    .A2(_041_),
    .ZN(_059_)
  );
  NAND2_X1 _145_ (
    .A1(_059_),
    .A2(_029_),
    .ZN(_060_)
  );
  AND2_X1 _146_ (
    .A1(_049_),
    .A2(_054_),
    .ZN(_061_)
  );
  AOI21_X1 _147_ (
    .A(_061_),
    .B1(_046_),
    .B2(_055_),
    .ZN(_062_)
  );
  OR2_X1 _148_ (
    .A1(_050_),
    .A2(_051_),
    .ZN(_063_)
  );
  INV_X1 _149_ (
    .A(_053_),
    .ZN(_064_)
  );
  OAI21_X1 _150_ (
    .A(_063_),
    .B1(_052_),
    .B2(_064_),
    .ZN(_065_)
  );
  AND2_X1 _151_ (
    .A1(_083_),
    .A2(_079_),
    .ZN(_066_)
  );
  XOR2_X1 _152_ (
    .A(_065_),
    .B(_066_),
    .Z(_067_)
  );
  AND3_X1 _153_ (
    .A1(_032_),
    .A2(_033_),
    .A3(_048_),
    .ZN(_068_)
  );
  XNOR2_X1 _154_ (
    .A(_067_),
    .B(_068_),
    .ZN(_069_)
  );
  XOR2_X1 _155_ (
    .A(_062_),
    .B(_069_),
    .Z(_070_)
  );
  XNOR2_X1 _156_ (
    .A(_060_),
    .B(_070_),
    .ZN(_005_)
  );
  NAND3_X1 _157_ (
    .A1(_059_),
    .A2(_029_),
    .A3(_070_),
    .ZN(_071_)
  );
  NAND2_X1 _158_ (
    .A1(_067_),
    .A2(_068_),
    .ZN(_072_)
  );
  OAI21_X1 _159_ (
    .A(_072_),
    .B1(_062_),
    .B2(_069_),
    .ZN(_073_)
  );
  NAND2_X1 _160_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_074_)
  );
  XNOR2_X1 _161_ (
    .A(_073_),
    .B(_074_),
    .ZN(_075_)
  );
  XNOR2_X1 _162_ (
    .A(_071_),
    .B(_075_),
    .ZN(_006_)
  );
  assign a = { \ha7.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \add.black3_2.pik , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.a  = { \ha7.c , \add.grey6.pik , \add.black5_4.pik , \add.black5_4.pkj , \add.black3_2.pik , ip_2_0, ip_0_1, ip_0_0 };
  assign \add.b  = { \fa4.cy , 4'h0, \ha0.s , ip_1_0, 1'h0 };
  assign \add.black3_2.gij  = \add.grey3.gik ;
  assign \add.black3_2.gik  = 1'h0;
  assign \add.black5_4.gij  = 1'h0;
  assign \add.black5_4.gik  = 1'h0;
  assign \add.black5_4.gkj  = 1'h0;
  assign \add.c0  = 1'h0;
  assign \add.g0_0  = 1'h0;
  assign \add.g1_0  = \add.c1 ;
  assign \add.g1_1  = \add.c1 ;
  assign \add.g2_0  = \add.c2 ;
  assign \add.g2_2  = \add.black3_2.gkj ;
  assign \add.g3_0  = \add.c3 ;
  assign \add.g3_2  = \add.grey3.gik ;
  assign \add.g3_3  = 1'h0;
  assign \add.g4_0  = \add.c4 ;
  assign \add.g4_4  = 1'h0;
  assign \add.g5_0  = \add.c5 ;
  assign \add.g5_4  = 1'h0;
  assign \add.g5_5  = 1'h0;
  assign \add.g6_0  = \add.c6 ;
  assign \add.g6_6  = 1'h0;
  assign \add.grey1.gij  = \add.c1 ;
  assign \add.grey1.gik  = \add.c1 ;
  assign \add.grey1.gkj  = 1'h0;
  assign \add.grey1.pik  = \add.p1_1 ;
  assign \add.grey2.gij  = \add.c2 ;
  assign \add.grey2.gik  = \add.black3_2.gkj ;
  assign \add.grey2.gkj  = \add.c1 ;
  assign \add.grey2.pik  = \add.black3_2.pkj ;
  assign \add.grey3.gij  = \add.c3 ;
  assign \add.grey3.gkj  = \add.c1 ;
  assign \add.grey3.pik  = \add.black3_2.pij ;
  assign \add.grey4.gij  = \add.c4 ;
  assign \add.grey4.gik  = 1'h0;
  assign \add.grey4.gkj  = \add.c3 ;
  assign \add.grey4.pik  = \add.black5_4.pkj ;
  assign \add.grey5.gij  = \add.c5 ;
  assign \add.grey5.gik  = 1'h0;
  assign \add.grey5.gkj  = \add.c3 ;
  assign \add.grey5.pik  = \add.black5_4.pij ;
  assign \add.grey6.gij  = \add.c6 ;
  assign \add.grey6.gik  = 1'h0;
  assign \add.grey6.gkj  = \add.c5 ;
  assign \add.p2_2  = \add.black3_2.pkj ;
  assign \add.p3_2  = \add.black3_2.pij ;
  assign \add.p3_3  = \add.black3_2.pik ;
  assign \add.p4_4  = \add.black5_4.pkj ;
  assign \add.p5_4  = \add.black5_4.pij ;
  assign \add.p5_5  = \add.black5_4.pik ;
  assign \add.p6_6  = \add.grey6.pik ;
  assign \add.s [1:0] = { \add.p1_1 , ip_0_0 };
  assign b = { \fa4.cy , 4'h0, \ha0.s , ip_1_0, 1'h0 };
  assign \fa0.a  = \fa0.h1.a ;
  assign \fa0.b  = \fa0.h1.b ;
  assign \fa0.c  = \fa0.h2.b ;
  assign \fa0.h2.a  = \fa0.h1.s ;
  assign \fa0.h2.s  = \add.black3_2.pik ;
  assign \fa0.sm  = \add.black3_2.pik ;
  assign \fa0.x  = \fa0.h1.c ;
  assign \fa0.y  = \fa0.h2.c ;
  assign \fa0.z  = \fa0.h1.s ;
  assign \fa1.a  = \fa1.h1.a ;
  assign \fa1.b  = \fa1.h1.b ;
  assign \fa1.c  = \fa0.cy ;
  assign \fa1.h2.a  = \fa1.h1.s ;
  assign \fa1.h2.b  = \fa0.cy ;
  assign \fa1.h2.s  = \add.black5_4.pkj ;
  assign \fa1.sm  = \add.black5_4.pkj ;
  assign \fa1.x  = \fa1.h1.c ;
  assign \fa1.y  = \fa1.h2.c ;
  assign \fa1.z  = \fa1.h1.s ;
  assign \fa2.a  = \fa2.h1.a ;
  assign \fa2.b  = \fa2.h1.b ;
  assign \fa2.c  = \fa2.h2.b ;
  assign \fa2.h2.a  = \fa2.h1.s ;
  assign \fa2.sm  = \fa2.h2.s ;
  assign \fa2.x  = \fa2.h1.c ;
  assign \fa2.y  = \fa2.h2.c ;
  assign \fa2.z  = \fa2.h1.s ;
  assign \fa3.a  = \fa2.h2.s ;
  assign \fa3.b  = \fa3.h1.b ;
  assign \fa3.c  = \fa1.cy ;
  assign \fa3.h1.a  = \fa2.h2.s ;
  assign \fa3.h2.a  = \fa3.h1.s ;
  assign \fa3.h2.b  = \fa1.cy ;
  assign \fa3.h2.s  = \add.black5_4.pik ;
  assign \fa3.sm  = \add.black5_4.pik ;
  assign \fa3.x  = \fa3.h1.c ;
  assign \fa3.y  = \fa3.h2.c ;
  assign \fa3.z  = \fa3.h1.s ;
  assign \fa4.a  = \fa4.h1.a ;
  assign \fa4.b  = \fa4.h1.b ;
  assign \fa4.c  = \fa3.cy ;
  assign \fa4.h2.a  = \fa4.h1.s ;
  assign \fa4.h2.b  = \fa3.cy ;
  assign \fa4.h2.s  = \add.grey6.pik ;
  assign \fa4.sm  = \add.grey6.pik ;
  assign \fa4.x  = \fa4.h1.c ;
  assign \fa4.y  = \fa4.h2.c ;
  assign \fa4.z  = \fa4.h1.s ;
  assign \ha0.c  = \fa0.h1.a ;
  assign \ha1.s  = \fa0.h1.b ;
  assign \ha2.s  = \fa0.h2.b ;
  assign \ha3.c  = \fa2.h2.b ;
  assign \ha4.b  = \ha1.c ;
  assign \ha4.s  = \fa1.h1.a ;
  assign \ha5.a  = \ha2.c ;
  assign \ha5.b  = \ha3.s ;
  assign \ha5.s  = \fa1.h1.b ;
  assign \ha6.a  = \ha4.c ;
  assign \ha6.b  = \ha5.c ;
  assign \ha6.c  = \fa4.h1.a ;
  assign \ha6.s  = \fa3.h1.b ;
  assign \ha7.b  = \fa2.cy ;
  assign \ha7.s  = \fa4.h1.b ;
  assign ip_0_2 = \ha0.a ;
  assign ip_0_3 = \ha1.a ;
  assign ip_1_1 = \ha0.b ;
  assign ip_1_2 = \ha1.b ;
  assign ip_1_3 = \ha3.a ;
  assign ip_2_1 = \ha2.a ;
  assign ip_2_2 = \ha3.b ;
  assign ip_2_3 = \fa2.h1.a ;
  assign ip_3_0 = \ha2.b ;
  assign ip_3_1 = \ha4.a ;
  assign ip_3_2 = \fa2.h1.b ;
  assign ip_3_3 = \ha7.a ;
  assign o = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign p0 = \fa0.h1.a ;
  assign p1 = \ha0.s ;
  assign p10 = \ha4.c ;
  assign p11 = \fa1.h1.a ;
  assign p12 = \ha5.c ;
  assign p13 = \fa1.h1.b ;
  assign p14 = \fa1.cy ;
  assign p15 = \add.black5_4.pkj ;
  assign p16 = \fa2.cy ;
  assign p17 = \fa2.h2.s ;
  assign p18 = \fa4.h1.a ;
  assign p19 = \fa3.h1.b ;
  assign p2 = \ha1.c ;
  assign p20 = \fa3.cy ;
  assign p21 = \add.black5_4.pik ;
  assign p22 = \ha7.c ;
  assign p23 = \fa4.h1.b ;
  assign p24 = \fa4.cy ;
  assign p25 = \add.grey6.pik ;
  assign p3 = \fa0.h1.b ;
  assign p4 = \ha2.c ;
  assign p5 = \fa0.h2.b ;
  assign p6 = \fa0.cy ;
  assign p7 = \add.black3_2.pik ;
  assign p8 = \fa2.h2.b ;
  assign p9 = \ha3.s ;
  assign s = { \add.s [7:2], \add.p1_1 , ip_0_0 };
  assign _080_ = y[0];
  assign _076_ = x[0];
  assign ip_0_0 = _007_;
  assign _081_ = y[1];
  assign _082_ = y[2];
  assign _083_ = y[3];
  assign _077_ = x[1];
  assign _078_ = x[2];
  assign _079_ = x[3];
  assign \add.p1_1  = _000_;
  assign \add.s [2] = _001_;
  assign \add.s [3] = _002_;
  assign \add.s [4] = _003_;
  assign \add.s [5] = _004_;
  assign \add.s [6] = _005_;
  assign \add.s [7] = _006_;
endmodule
